# GENERATED BY bindsmith — do not edit.
#
# jnigen looks a class up by name when Dart first calls it, which
# R8 cannot see, so every class the binding uses is kept whole.

-keep class com.example.ktgreeter.KtGreeter { *; }
-keep class com.example.ktgreeter.KtGreeter$Companion { *; }
-keep class com.example.ktgreeter.Listener { *; }
-keep class com.example.ktgreeter.Reply { *; }
-keep class com.example.ktgreeter.Reply$Failed { *; }
-keep class com.example.ktgreeter.Reply$Ok { *; }
-keep class com.example.ktgreeter.Volume { *; }

# A suspend fun resumes Dart through kotlin.coroutines, which
# package:jni calls by name as well.
-keep class kotlin.coroutines.** { *; }
