// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'package:bindsmith_runtime/bindsmith_runtime.dart';

import 'src/generated/linux/dbus.g.dart' as linux;

final class ComExampleGreeter {
  ComExampleGreeter._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  /// Invokes com.example.Greeter.Greet().
  @BindsmithVerify(
    'linux: async result needs a completion-handler wrapper; the raw binding value is returned',
  )
  Future<String> callGreet(String name) =>
      (_impl as linux.ComExampleGreeter).callGreet(name);

  /// Gets com.example.Greeter.Version.
  @BindsmithVerify(
    'linux: async result needs a completion-handler wrapper; the raw binding value is returned',
  )
  Future<String> getVersion() =>
      (_impl as linux.ComExampleGreeter).getVersion();
}

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);

// Not emitted by the facade (see `bindsmith verify`):
//   linux ComExampleGreeter.greeted — hidden by fixup ComExampleGreeter.greeted
