// GENERATED BY bindsmith — do not edit.
// AUTO GENERATED BY JNIGEN 1.0.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.example.greeter.Greeter`
///
/// Greets people, with a couple of Java shapes the driver has to map.
extension type Greeter._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'com/example/greeter/Greeter');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Greeter> type = $Greeter$Type$();
  static final _id_DEFAULT_PREFIX = _class.staticFieldId(
    r'DEFAULT_PREFIX',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String DEFAULT_PREFIX`
  /// The returned object must be released after use, by calling the [release] method.
  ///
  /// Default separator between the prefix and the name.
  static jni$_.JString? get DEFAULT_PREFIX =>
      _id_DEFAULT_PREFIX.getNullable(_class, jni$_.JString.type)
          as jni$_.JString?;

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Greeter() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer).object<Greeter>();
  }

  static final _id_new$1 = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String prefix)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Greeter.new$1(jni$_.JString? prefix) {
    final _$$classRef = _class.reference;
    final _$prefix = prefix?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$prefix.pointer,
    ).object<Greeter>();
  }

  static final _id_version = _class.staticMethodId(r'version', r'()I');

  static final _version =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public int version()`
  ///
  /// The library version.
  static core$_.int version() {
    final _$$classRef = _class.reference;
    return _version(_$$classRef.pointer, _id_version.pointer).integer;
  }
}

extension Greeter$$Methods on Greeter {
  static final _id_count = Greeter._class.instanceFieldId(r'count', r'I');

  /// from: `public int count`
  ///
  /// Number of greetings this instance has produced.
  core$_.int get count =>
      _id_count.getNullable(this, jni$_.jint.type) as core$_.int;

  /// from: `public int count`
  ///
  /// Number of greetings this instance has produced.
  set count(core$_.int value) => _id_count.set(this, jni$_.jint.type, value);

  static final _id_greet = Greeter._class.instanceMethodId(
    r'greet',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _greet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.String greet(java.lang.String name)`
  /// The returned object must be released after use, by calling the [release] method.
  ///
  /// Greets {@code name}.
  ///@param name The person to greet.
  jni$_.JString? greet(jni$_.JString? name) {
    final _$$selfRef = reference;
    final _$name = name?.reference ?? jni$_.jNullReference;
    return _greet(
      _$$selfRef.pointer,
      _id_greet.pointer,
      _$name.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_greetAll = Greeter._class.instanceMethodId(
    r'greetAll',
    r'(Ljava/util/List;)Ljava/util/List;',
  );

  static final _greetAll =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.List<java.lang.String> greetAll(java.util.List<java.lang.String> names)`
  /// The returned object must be released after use, by calling the [release] method.
  ///
  /// Greets everyone in the list.
  jni$_.JList<jni$_.JString?>? greetAll(jni$_.JList<jni$_.JString?>? names) {
    final _$$selfRef = reference;
    final _$names = names?.reference ?? jni$_.jNullReference;
    return _greetAll(
      _$$selfRef.pointer,
      _id_greetAll.pointer,
      _$names.pointer,
    ).object<jni$_.JList<jni$_.JString?>?>();
  }

  static final _id_greetAsync = Greeter._class.instanceMethodId(
    r'greetAsync',
    r'(Ljava/lang/String;Lcom/example/greeter/Greeter$Listener;)V',
  );

  static final _greetAsync =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void greetAsync(java.lang.String name, com.example.greeter.Greeter$Listener listener)`
  ///
  /// Greets {@code name} and hands the result to {@code listener}.
  void greetAsync(jni$_.JString? name, Greeter$Listener? listener) {
    final _$$selfRef = reference;
    final _$name = name?.reference ?? jni$_.jNullReference;
    final _$listener = listener?.reference ?? jni$_.jNullReference;
    _greetAsync(
      _$$selfRef.pointer,
      _id_greetAsync.pointer,
      _$name.pointer,
      _$listener.pointer,
    ).check();
  }
}

final class $Greeter$Type$ extends jni$_.JType<Greeter> {
  @jni$_.internal
  const $Greeter$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/greeter/Greeter;';
}

/// from: `com.example.greeter.Greeter$Listener`
///
/// Receives a greeting.
extension type Greeter$Listener._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/greeter/Greeter$Listener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Greeter$Listener> type = $Greeter$Listener$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $Greeter$Listener> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onGreeting(Ljava/lang/String;)V') {
        _$impls[$p]!.onGreeting(($a![0] as jni$_.JString?));
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $Greeter$Listener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.example.greeter.Greeter$Listener',
      $p,
      _$invokePointer,
      [if ($impl.onGreeting$async) r'onGreeting(Ljava/lang/String;)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory Greeter$Listener.implement($Greeter$Listener $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<Greeter$Listener>();
  }
}

extension Greeter$Listener$$Methods on Greeter$Listener {
  static final _id_onGreeting = Greeter$Listener._class.instanceMethodId(
    r'onGreeting',
    r'(Ljava/lang/String;)V',
  );

  static final _onGreeting =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onGreeting(java.lang.String greeting)`
  void onGreeting(jni$_.JString? greeting) {
    final _$$selfRef = reference;
    final _$greeting = greeting?.reference ?? jni$_.jNullReference;
    _onGreeting(
      _$$selfRef.pointer,
      _id_onGreeting.pointer,
      _$greeting.pointer,
    ).check();
  }
}

abstract base mixin class $Greeter$Listener {
  factory $Greeter$Listener({
    required void Function(jni$_.JString? greeting) onGreeting,
    core$_.bool onGreeting$async,
  }) = _$Greeter$Listener;

  void onGreeting(jni$_.JString? greeting);
  core$_.bool get onGreeting$async => false;
}

final class _$Greeter$Listener with $Greeter$Listener {
  _$Greeter$Listener({
    required void Function(jni$_.JString? greeting) onGreeting,
    this.onGreeting$async = false,
  }) : _onGreeting = onGreeting;

  final void Function(jni$_.JString? greeting) _onGreeting;
  final core$_.bool onGreeting$async;

  void onGreeting(jni$_.JString? greeting) {
    return _onGreeting(greeting);
  }
}

final class $Greeter$Listener$Type$ extends jni$_.JType<Greeter$Listener> {
  @jni$_.internal
  const $Greeter$Listener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/greeter/Greeter$Listener;';
}

/// from: `com.example.greeter.Greeter$Volume`
///
/// How loudly to greet.
extension type Greeter$Volume._(jni$_.JObject _$this) implements Enum {
  static final _class = jni$_.JClass.forName(
    r'com/example/greeter/Greeter$Volume',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Greeter$Volume> type = $Greeter$Volume$Type$();
  static final _id_QUIET = _class.staticFieldId(
    r'QUIET',
    r'Lcom/example/greeter/Greeter$Volume;',
  );

  /// from: `static public final com.example.greeter.Greeter$Volume QUIET`
  /// The returned object must be released after use, by calling the [release] method.
  static Greeter$Volume get QUIET =>
      _id_QUIET.get(_class, Greeter$Volume.type) as Greeter$Volume;

  static final _id_NORMAL = _class.staticFieldId(
    r'NORMAL',
    r'Lcom/example/greeter/Greeter$Volume;',
  );

  /// from: `static public final com.example.greeter.Greeter$Volume NORMAL`
  /// The returned object must be released after use, by calling the [release] method.
  static Greeter$Volume get NORMAL =>
      _id_NORMAL.get(_class, Greeter$Volume.type) as Greeter$Volume;

  static final _id_LOUD = _class.staticFieldId(
    r'LOUD',
    r'Lcom/example/greeter/Greeter$Volume;',
  );

  /// from: `static public final com.example.greeter.Greeter$Volume LOUD`
  /// The returned object must be released after use, by calling the [release] method.
  static Greeter$Volume get LOUD =>
      _id_LOUD.get(_class, Greeter$Volume.type) as Greeter$Volume;

  static final _id_values = _class.staticMethodId(
    r'values',
    r'()[Lcom/example/greeter/Greeter$Volume;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public com.example.greeter.Greeter$Volume[] values()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<Greeter$Volume?>? values() {
    final _$$classRef = _class.reference;
    return _values(
      _$$classRef.pointer,
      _id_values.pointer,
    ).object<jni$_.JArray<Greeter$Volume?>?>();
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/lang/String;)Lcom/example/greeter/Greeter$Volume;',
  );

  static final _valueOf =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.example.greeter.Greeter$Volume valueOf(java.lang.String name)`
  /// The returned object must be released after use, by calling the [release] method.
  static Greeter$Volume? valueOf(jni$_.JString? name) {
    final _$$classRef = _class.reference;
    final _$name = name?.reference ?? jni$_.jNullReference;
    return _valueOf(
      _$$classRef.pointer,
      _id_valueOf.pointer,
      _$name.pointer,
    ).object<Greeter$Volume?>();
  }
}

final class $Greeter$Volume$Type$ extends jni$_.JType<Greeter$Volume> {
  @jni$_.internal
  const $Greeter$Volume$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/greeter/Greeter$Volume;';
}

/// from: `java.lang.Enum`
///
/// WARNING: Enum is a stub. To generate bindings for this class, include
/// java.lang.Enum in your config's classes list.
///
extension type Enum._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Enum> type = $Enum$Type$();
}

final class $Enum$Type$ extends jni$_.JType<Enum> {
  @jni$_.internal
  const $Enum$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Enum;';
}
