// GENERATED BY bindsmith — do not edit.
// AUTO GENERATED BY JNIGEN 1.0.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.example.ktgreeter.KtGreeter$Companion`
extension type KtGreeter$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/ktgreeter/KtGreeter$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<KtGreeter$Companion> type =
      $KtGreeter$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory KtGreeter$Companion(
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<KtGreeter$Companion>();
  }
}

extension KtGreeter$Companion$$Methods on KtGreeter$Companion {
  static final _id_version = KtGreeter$Companion._class.instanceMethodId(
    r'version',
    r'()I',
  );

  static final _version =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun version(): kotlin.Int`
  core$_.int version() {
    final _$$selfRef = reference;
    return _version(_$$selfRef.pointer, _id_version.pointer).integer;
  }
}

final class $KtGreeter$Companion$Type$
    extends jni$_.JType<KtGreeter$Companion> {
  @jni$_.internal
  const $KtGreeter$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/KtGreeter$Companion;';
}

/// from: `com.example.ktgreeter.KtGreeter`
extension type KtGreeter._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/ktgreeter/KtGreeter',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<KtGreeter> type = $KtGreeter$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/example/ktgreeter/KtGreeter$Companion;',
  );

  /// from: `static public final com.example.ktgreeter.KtGreeter$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static KtGreeter$Companion get Companion =>
      _id_Companion.get(_class, KtGreeter$Companion.type)
          as KtGreeter$Companion;

  static final _id_DEFAULT_PREFIX = _class.staticFieldId(
    r'DEFAULT_PREFIX',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String DEFAULT_PREFIX`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString get DEFAULT_PREFIX =>
      _id_DEFAULT_PREFIX.get(_class, jni$_.JString.type) as jni$_.JString;

  static final _id_new$ = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory KtGreeter(jni$_.JString string) {
    final _$$classRef = _class.reference;
    final _$string = string.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$string.pointer,
    ).object<KtGreeter>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(java.lang.String string, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory KtGreeter.new$1(
    jni$_.JString? string,
    core$_.int i,
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$string.pointer,
      i,
      _$defaultConstructorMarker.pointer,
    ).object<KtGreeter>();
  }

  static final _id_new$2 = _class.constructorId(r'()V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory KtGreeter.new$2() {
    final _$$classRef = _class.reference;
    return _new$2(_$$classRef.pointer, _id_new$2.pointer).object<KtGreeter>();
  }
}

extension KtGreeter$$Methods on KtGreeter {
  static final _id_greet = KtGreeter._class.instanceMethodId(
    r'greet',
    r'(Ljava/lang/String;Lcom/example/ktgreeter/Volume;)Ljava/lang/String;',
  );

  static final _greet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun greet(name: kotlin.String, volume: com.example.ktgreeter.Volume): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString greet(jni$_.JString string, Volume volume) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$volume = volume.reference;
    return _greet(
      _$$selfRef.pointer,
      _id_greet.pointer,
      _$string.pointer,
      _$volume.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_greetAll = KtGreeter._class.instanceMethodId(
    r'greetAll',
    r'(Ljava/util/List;)Lkotlinx/coroutines/flow/Flow;',
  );

  static final _greetAll =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun greetAll(names: kotlin.collections.List<kotlin.String>): kotlinx.coroutines.flow.Flow<kotlin.String>`
  /// The returned object must be released after use, by calling the [release] method.
  Flow greetAll(jni$_.JList<jni$_.JString> list) {
    final _$$selfRef = reference;
    final _$list = list.reference;
    return _greetAll(
      _$$selfRef.pointer,
      _id_greetAll.pointer,
      _$list.pointer,
    ).object<Flow>();
  }

  static final _id_greetSlowly = KtGreeter._class.instanceMethodId(
    r'greetSlowly',
    r'(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _greetSlowly =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public suspend fun greetSlowly(name: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> greetSlowly(jni$_.JString string) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$$selfRef = reference;
    final _$string = string.reference;
    final $r = _greetSlowly(
      _$$selfRef.pointer,
      _id_greetSlowly.pointer,
      _$string.pointer,
      _$continuation.pointer,
    ).object<jni$_.JObject>();
    _$continuation.release();
    jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
        jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)),
      );
      if ($o.isInstanceOf(jni$_.result$Class)) {
        $o = jni$_.resultValueField.get($o, const jni$_.$JObject$Type$());
      } else if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e = jni$_.failureExceptionField.get(
          $o,
          const jni$_.$JObject$Type$(),
        );
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(jni$_.JString.type, releaseOriginal: true);
  }

  static final _id_tryGreet = KtGreeter._class.instanceMethodId(
    r'tryGreet',
    r'(Ljava/lang/String;)Lcom/example/ktgreeter/Reply;',
  );

  static final _tryGreet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun tryGreet(name: kotlin.String): com.example.ktgreeter.Reply`
  /// The returned object must be released after use, by calling the [release] method.
  Reply tryGreet(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _tryGreet(
      _$$selfRef.pointer,
      _id_tryGreet.pointer,
      _$string.pointer,
    ).object<Reply>();
  }

  static final _id_shout = KtGreeter._class.instanceMethodId(
    r'shout',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _shout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun shout(name: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString shout(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _shout(
      _$$selfRef.pointer,
      _id_shout.pointer,
      _$string.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_shout$1 = KtGreeter._class.instanceMethodId(
    r'shout',
    r'(Ljava/lang/String;I)Ljava/lang/String;',
  );

  static final _shout$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun shout(name: kotlin.String, times: kotlin.Int): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString shout$1(jni$_.JString string, core$_.int i) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _shout$1(
      _$$selfRef.pointer,
      _id_shout$1.pointer,
      _$string.pointer,
      i,
    ).object<jni$_.JString>();
  }

  static final _id_nickname = KtGreeter._class.instanceMethodId(
    r'nickname',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _nickname =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun nickname(name: kotlin.String): kotlin.String?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? nickname(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _nickname(
      _$$selfRef.pointer,
      _id_nickname.pointer,
      _$string.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_greetTo = KtGreeter._class.instanceMethodId(
    r'greetTo',
    r'(Ljava/lang/String;Lcom/example/ktgreeter/Listener;)V',
  );

  static final _greetTo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun greetTo(name: kotlin.String, listener: com.example.ktgreeter.Listener): kotlin.Unit`
  void greetTo(jni$_.JString string, Listener listener) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$listener = listener.reference;
    _greetTo(
      _$$selfRef.pointer,
      _id_greetTo.pointer,
      _$string.pointer,
      _$listener.pointer,
    ).check();
  }
}

final class $KtGreeter$Type$ extends jni$_.JType<KtGreeter> {
  @jni$_.internal
  const $KtGreeter$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/KtGreeter;';
}

/// from: `com.example.ktgreeter.Listener`
extension type Listener._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'com/example/ktgreeter/Listener');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Listener> type = $Listener$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $Listener> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onGreeting(Ljava/lang/String;)V') {
        _$impls[$p]!.onGreeting(($a![0] as jni$_.JString));
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(jni$_.JImplementer implementer, $Listener $impl) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(r'com.example.ktgreeter.Listener', $p, _$invokePointer, [
      if ($impl.onGreeting$async) r'onGreeting(Ljava/lang/String;)V',
    ]);
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory Listener.implement($Listener $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<Listener>();
  }
}

extension Listener$$Methods on Listener {
  static final _id_onGreeting = Listener._class.instanceMethodId(
    r'onGreeting',
    r'(Ljava/lang/String;)V',
  );

  static final _onGreeting =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onGreeting(greeting: kotlin.String): kotlin.Unit`
  void onGreeting(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    _onGreeting(
      _$$selfRef.pointer,
      _id_onGreeting.pointer,
      _$string.pointer,
    ).check();
  }
}

abstract base mixin class $Listener {
  factory $Listener({
    required void Function(jni$_.JString string) onGreeting,
    core$_.bool onGreeting$async,
  }) = _$Listener;

  void onGreeting(jni$_.JString string);
  core$_.bool get onGreeting$async => false;
}

final class _$Listener with $Listener {
  _$Listener({
    required void Function(jni$_.JString string) onGreeting,
    this.onGreeting$async = false,
  }) : _onGreeting = onGreeting;

  final void Function(jni$_.JString string) _onGreeting;
  final core$_.bool onGreeting$async;

  void onGreeting(jni$_.JString string) {
    return _onGreeting(string);
  }
}

final class $Listener$Type$ extends jni$_.JType<Listener> {
  @jni$_.internal
  const $Listener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/Listener;';
}

/// from: `com.example.ktgreeter.Reply$Failed`
extension type Reply$Failed._(jni$_.JObject _$this) implements Reply {
  static final _class = jni$_.JClass.forName(
    r'com/example/ktgreeter/Reply$Failed',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Reply$Failed> type = $Reply$Failed$Type$();
  static final _id_new$ = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Reply$Failed(jni$_.JString string) {
    final _$$classRef = _class.reference;
    final _$string = string.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$string.pointer,
    ).object<Reply$Failed>();
  }
}

extension Reply$Failed$$Methods on Reply$Failed {
  static final _id_get$reason = Reply$Failed._class.instanceMethodId(
    r'getReason',
    r'()Ljava/lang/String;',
  );

  static final _get$reason =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getReason()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get reason {
    final _$$selfRef = reference;
    return _get$reason(
      _$$selfRef.pointer,
      _id_get$reason.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_component1 = Reply$Failed._class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/String;',
  );

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString component1() {
    final _$$selfRef = reference;
    return _component1(
      _$$selfRef.pointer,
      _id_component1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_copy = Reply$Failed._class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/String;)Lcom/example/ktgreeter/Reply$Failed;',
  );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(reason: kotlin.String): com.example.ktgreeter.Reply.Failed`
  /// The returned object must be released after use, by calling the [release] method.
  Reply$Failed copy(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _copy(
      _$$selfRef.pointer,
      _id_copy.pointer,
      _$string.pointer,
    ).object<Reply$Failed>();
  }

  static final _id_toString$1 = Reply$Failed._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    final _$$selfRef = reference;
    return _toString$1(
      _$$selfRef.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_hashCode$1 = Reply$Failed._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_equals = Reply$Failed._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(jni$_.JObject? object) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }
}

final class $Reply$Failed$Type$ extends jni$_.JType<Reply$Failed> {
  @jni$_.internal
  const $Reply$Failed$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/Reply$Failed;';
}

/// from: `com.example.ktgreeter.Reply$Ok`
extension type Reply$Ok._(jni$_.JObject _$this) implements Reply {
  static final _class = jni$_.JClass.forName(r'com/example/ktgreeter/Reply$Ok');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Reply$Ok> type = $Reply$Ok$Type$();
  static final _id_new$ = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Reply$Ok(jni$_.JString string) {
    final _$$classRef = _class.reference;
    final _$string = string.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$string.pointer,
    ).object<Reply$Ok>();
  }
}

extension Reply$Ok$$Methods on Reply$Ok {
  static final _id_get$text = Reply$Ok._class.instanceMethodId(
    r'getText',
    r'()Ljava/lang/String;',
  );

  static final _get$text =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getText()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get text {
    final _$$selfRef = reference;
    return _get$text(
      _$$selfRef.pointer,
      _id_get$text.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_component1 = Reply$Ok._class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/String;',
  );

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString component1() {
    final _$$selfRef = reference;
    return _component1(
      _$$selfRef.pointer,
      _id_component1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_copy = Reply$Ok._class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/String;)Lcom/example/ktgreeter/Reply$Ok;',
  );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(text: kotlin.String): com.example.ktgreeter.Reply.Ok`
  /// The returned object must be released after use, by calling the [release] method.
  Reply$Ok copy(jni$_.JString string) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _copy(
      _$$selfRef.pointer,
      _id_copy.pointer,
      _$string.pointer,
    ).object<Reply$Ok>();
  }

  static final _id_toString$1 = Reply$Ok._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    final _$$selfRef = reference;
    return _toString$1(
      _$$selfRef.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_hashCode$1 = Reply$Ok._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_equals = Reply$Ok._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(jni$_.JObject? object) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }
}

final class $Reply$Ok$Type$ extends jni$_.JType<Reply$Ok> {
  @jni$_.internal
  const $Reply$Ok$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/Reply$Ok;';
}

/// from: `com.example.ktgreeter.Reply`
extension type Reply._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'com/example/ktgreeter/Reply');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Reply> type = $Reply$Type$();
}

final class $Reply$Type$ extends jni$_.JType<Reply> {
  @jni$_.internal
  const $Reply$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/Reply;';
}

/// from: `com.example.ktgreeter.Volume`
extension type Volume._(jni$_.JObject _$this) implements Enum {
  static final _class = jni$_.JClass.forName(r'com/example/ktgreeter/Volume');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Volume> type = $Volume$Type$();
  static final _id_QUIET = _class.staticFieldId(
    r'QUIET',
    r'Lcom/example/ktgreeter/Volume;',
  );

  /// from: `static public final com.example.ktgreeter.Volume QUIET`
  /// The returned object must be released after use, by calling the [release] method.
  static Volume get QUIET => _id_QUIET.get(_class, Volume.type) as Volume;

  static final _id_NORMAL = _class.staticFieldId(
    r'NORMAL',
    r'Lcom/example/ktgreeter/Volume;',
  );

  /// from: `static public final com.example.ktgreeter.Volume NORMAL`
  /// The returned object must be released after use, by calling the [release] method.
  static Volume get NORMAL => _id_NORMAL.get(_class, Volume.type) as Volume;

  static final _id_LOUD = _class.staticFieldId(
    r'LOUD',
    r'Lcom/example/ktgreeter/Volume;',
  );

  /// from: `static public final com.example.ktgreeter.Volume LOUD`
  /// The returned object must be released after use, by calling the [release] method.
  static Volume get LOUD => _id_LOUD.get(_class, Volume.type) as Volume;

  static final _id_values = _class.staticMethodId(
    r'values',
    r'()[Lcom/example/ktgreeter/Volume;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public com.example.ktgreeter.Volume[] values()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<Volume?>? values() {
    final _$$classRef = _class.reference;
    return _values(
      _$$classRef.pointer,
      _id_values.pointer,
    ).object<jni$_.JArray<Volume?>?>();
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/lang/String;)Lcom/example/ktgreeter/Volume;',
  );

  static final _valueOf =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.example.ktgreeter.Volume valueOf(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static Volume? valueOf(jni$_.JString? string) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _valueOf(
      _$$classRef.pointer,
      _id_valueOf.pointer,
      _$string.pointer,
    ).object<Volume?>();
  }

  static final _id_get$entries = _class.staticMethodId(
    r'getEntries',
    r'()Lkotlin/enums/EnumEntries;',
  );

  static final _get$entries =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public kotlin.enums.EnumEntries<com.example.ktgreeter.Volume> getEntries()`
  /// The returned object must be released after use, by calling the [release] method.
  static EnumEntries get entries {
    final _$$classRef = _class.reference;
    return _get$entries(
      _$$classRef.pointer,
      _id_get$entries.pointer,
    ).object<EnumEntries>();
  }
}

final class $Volume$Type$ extends jni$_.JType<Volume> {
  @jni$_.internal
  const $Volume$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/ktgreeter/Volume;';
}

/// from: `kotlin.jvm.internal.DefaultConstructorMarker`
///
/// WARNING: DefaultConstructorMarker is a stub. To generate bindings for this class, include
/// kotlin.jvm.internal.DefaultConstructorMarker in your config's classes list.
///
extension type DefaultConstructorMarker._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<DefaultConstructorMarker> type =
      $DefaultConstructorMarker$Type$();
}

final class $DefaultConstructorMarker$Type$
    extends jni$_.JType<DefaultConstructorMarker> {
  @jni$_.internal
  const $DefaultConstructorMarker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/jvm/internal/DefaultConstructorMarker;';
}

/// from: `kotlinx.coroutines.flow.Flow`
///
/// WARNING: Flow is a stub. To generate bindings for this class, include
/// kotlinx.coroutines.flow.Flow in your config's classes list.
///
extension type Flow._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Flow> type = $Flow$Type$();
}

final class $Flow$Type$ extends jni$_.JType<Flow> {
  @jni$_.internal
  const $Flow$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlinx/coroutines/flow/Flow;';
}

/// from: `kotlin.coroutines.Continuation`
///
/// WARNING: Continuation is a stub. To generate bindings for this class, include
/// kotlin.coroutines.Continuation in your config's classes list.
///
extension type Continuation._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Continuation> type = $Continuation$Type$();
}

final class $Continuation$Type$ extends jni$_.JType<Continuation> {
  @jni$_.internal
  const $Continuation$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/coroutines/Continuation;';
}

/// from: `java.lang.Enum`
///
/// WARNING: Enum is a stub. To generate bindings for this class, include
/// java.lang.Enum in your config's classes list.
///
extension type Enum._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Enum> type = $Enum$Type$();
}

final class $Enum$Type$ extends jni$_.JType<Enum> {
  @jni$_.internal
  const $Enum$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Enum;';
}

/// from: `kotlin.enums.EnumEntries`
///
/// WARNING: EnumEntries is a stub. To generate bindings for this class, include
/// kotlin.enums.EnumEntries in your config's classes list.
///
extension type EnumEntries._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<EnumEntries> type = $EnumEntries$Type$();
}

final class $EnumEntries$Type$ extends jni$_.JType<EnumEntries> {
  @jni$_.internal
  const $EnumEntries$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/enums/EnumEntries;';
}
