// GENERATED BY bindsmith — do not edit.
#include "shim.g.h"

#include <cstdlib>
#include <cstring>
#include <exception>
#include <string>

#include "greeter.h"

namespace {

/// An exception unwinding out of `extern "C"` is undefined behaviour, so the
/// message is recorded here instead and the call returns a zero value.
thread_local std::string bindsmith_error;
thread_local bool bindsmith_failed = false;

template <typename Body>
auto bindsmith_guard(Body body) -> decltype(body()) {
  bindsmith_failed = false;
  try {
    return body();
  } catch (const std::exception& error) {
    bindsmith_error = error.what();
  } catch (...) {
    bindsmith_error = "unknown C++ exception";
  }
  bindsmith_failed = true;
  return decltype(body())();
}

/// Copies onto the C heap, so the result outlives the temporary it came from
/// and `greeter_free_string` can release it.
char* bindsmith_copy(const std::string& value) {
  char* out = static_cast<char*>(std::malloc(value.size() + 1));
  if (out != NULL) {
    std::memcpy(out, value.c_str(), value.size() + 1);
  }
  return out;
}

}  // namespace

extern "C" {

const char* greeter_last_error(void) {
  return bindsmith_failed ? bindsmith_error.c_str() : NULL;
}

void greeter_free_string(char* value) {
  std::free(value);
}

greeter_Greeter* greeter_Greeter_new(const char* prefix) {
  return bindsmith_guard([&]() -> greeter_Greeter* {
    return reinterpret_cast<greeter_Greeter*>(new greeter::Greeter(std::string(prefix ? prefix : "")));
  });
}

char* greeter_Greeter_Greet(greeter_Greeter* self, const char* name) {
  return bindsmith_guard([&]() -> char* {
    return bindsmith_copy(reinterpret_cast<greeter::Greeter*>(self)->Greet(std::string(name ? name : "")));
  });
}

void greeter_Greeter_SetPrefix(greeter_Greeter* self, const char* prefix) {
  return bindsmith_guard([&]() -> void {
    reinterpret_cast<greeter::Greeter*>(self)->SetPrefix(std::string(prefix ? prefix : ""));
  });
}

int greeter_Greeter_Count(greeter_Greeter* self) {
  return bindsmith_guard([&]() -> int {
    return reinterpret_cast<greeter::Greeter*>(self)->Count();
  });
}

int greeter_Greeter_Version(void) {
  return bindsmith_guard([&]() -> int {
    return greeter::Greeter::Version();
  });
}

void greeter_Greeter_delete(greeter_Greeter* self) {
  delete reinterpret_cast<greeter::Greeter*>(self);
}

}  // extern "C"
