// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'package:bindsmith_runtime/bindsmith_runtime.dart';
import 'package:jni/jni.dart';

import 'src/generated/android/jvm.g.dart' as android;

/// A class that provides system information related to biometrics (e.g. fingerprint, face, etc.).
///
/// On devices running Android 10 (API 29) and above, this will query the framework's version of
/// android.hardware.biometrics.BiometricManager. On Android 9.0 (API 28) and prior
/// versions, this will query androidx.core.hardware.fingerprint.FingerprintManagerCompat.
/// @see BiometricPrompt To prompt the user to authenticate with their biometric.
final class BiometricManager {
  BiometricManager._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  /// Checks if the user can authenticate with biometrics. This requires at least one biometric
  /// sensor to be present, enrolled, and available on the device.
  /// @return \#BIOMETRIC_SUCCESS if the user can authenticate with biometrics. Otherwise,
  /// returns an error code indicating why the user can't authenticate, or
  /// \#BIOMETRIC_STATUS_UNKNOWN if it is unknown whether the user can authenticate.
  /// @deprecated Use \#canAuthenticate(int) instead.
  int canAuthenticate() =>
      (_impl as android.BiometricManager).canAuthenticate();

  /// Checks if the user can authenticate with an authenticator that meets the given requirements.
  /// This requires at least one of the specified authenticators to be present, enrolled, and
  /// available on the device.
  ///
  /// Note that not all combinations of authenticator types are supported prior to Android 11
  /// (API 30). Specifically, `DEVICE_CREDENTIAL` alone is unsupported prior to API 30, and
  /// `BIOMETRIC_STRONG | DEVICE_CREDENTIAL` is unsupported on API 28-29. Developers that
  /// wish to check for the presence of a PIN, pattern, or password on these versions should
  /// instead use KeyguardManager\#isDeviceSecure().
  ///                      be used for authentication.
  /// @return \#BIOMETRIC_SUCCESS if the user can authenticate with an allowed
  /// authenticator. Otherwise, returns \#BIOMETRIC_STATUS_UNKNOWN or an error code
  /// indicating why the user can't authenticate.
  /// - [authenticators]: A bit field representing the types of Authenticators that may
  int canAuthenticate$1(int authenticators) =>
      (_impl as android.BiometricManager).canAuthenticate$1(authenticators);
}

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);

// Not emitted by the facade (see `bindsmith verify`):
//   android BiometricManager$Strings — not in the pull list; jnigen emitted a stub. Add androidx.biometric.BiometricManager$Strings to `classes` to bind it; not in include list
//   android BiometricManager.from — hidden by fixup BiometricManager.from
//   android BiometricManager.getStrings — hidden by fixup BiometricManager.getStrings
//   android Context — not in the pull list; jnigen emitted a stub. Add android.content.Context to `classes` to bind it; not in include list
