// GENERATED BY bindsmith — do not edit.
package com.example.ktgreeter

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch

/**
 * The parts of `KtGreeter` that JNI cannot reach on its own: a `Flow` has no
 * JNI surface; a default argument never crosses.
 */
class KtGreeterBridge(val wrapped: KtGreeter) {
  private val scope = CoroutineScope(Dispatchers.Default)

  /**
   * Cancels every collection this bridge started.
   */
  fun close() = scope.cancel()

  /**
   * Receives what `KtGreeter.greetAll` emits.
   *
   * Implement it from Dart with `GreetAllSink.implement`.
   */
  interface GreetAllSink {
    fun onValue(value: String)

    fun onError(error: Throwable)

    fun onDone()
  }

  /**
   * One greeting per name, emitted as a cold flow.
   *
   * Collects `KtGreeter.greetAll` into [sink] until it ends, fails, or the
   * returned handle is closed.
   *
   * A `Flow` is an object with no JNI surface, so this listener pair is what
   * the facade turns back into a `Stream`.
   */
  fun greetAll(names: List<String>, sink: GreetAllSink): AutoCloseable {
    val job = scope.launch {
      try {
        wrapped.greetAll(names = names).collect { sink.onValue(it) }
        sink.onDone()
      } catch (error: Throwable) {
        sink.onError(error)
      }
    }
    return AutoCloseable { job.cancel() }
  }

  /**
   * Greets [name], at [volume].
   *
   * `KtGreeter.greet` without `volume`.
   *
   * Kotlin compiles a default argument to a synthetic `greet$default` taking a
   * bitmask, so Dart only ever sees the full arity. Annotate the Kotlin
   * declaration with `@JvmOverloads` to bind it directly instead.
   */
  fun greet(name: String): String =
    wrapped.greet(name = name)
}

/**
 * The parts of `Reply` that JNI cannot reach on its own: a sealed subclass is
 * invisible.
 */
class ReplyBridge(val wrapped: Reply) {
  /**
   * The simple name of the subclass this value actually is: one of `Ok`,
   * `Failed`.
   */
  val kind: String
    get() = wrapped.javaClass.simpleName

  /**
   * The value as `Ok`, or `null` when it is not one.
   *
   * JNI can only reinterpret a reference; this cast is checked.
   */
  fun asOk(): Reply.Ok? =
    wrapped as? Reply.Ok

  /**
   * The value as `Failed`, or `null` when it is not one.
   *
   * JNI can only reinterpret a reference; this cast is checked.
   */
  fun asFailed(): Reply.Failed? =
    wrapped as? Reply.Failed
}
