// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'dart:js_interop';

import 'package:bindsmith_runtime/bindsmith_runtime.dart';

import 'src/generated/web/dts.g.dart' as web;

/// A Chart.js chart instance (subset of chart.js 4.x).
final class Chart {
  Chart._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  @BindsmithVerify(
    'web: unknown type CanvasRenderingContext2D is bound as JSAny?',
  )
  factory Chart(JSAny? item, ChartConfiguration config) =>
      Chart._(web.Chart(item, (config._impl as web.ChartConfiguration)));

  /// Destroys the chart.
  void destroy() {
    (_impl as web.Chart).destroy();
  }

  String get id => (_impl as web.Chart).id;

  /// Updates the chart after data changes.
  void update() {
    (_impl as web.Chart).update();
  }
}

/// Options for constructing a Chart.
final class ChartConfiguration {
  ChartConfiguration._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  /// Creates a JavaScript object literal with these properties.
  factory ChartConfiguration({required String type, required ChartData data}) =>
      ChartConfiguration._(
        web.ChartConfiguration(type: type, data: (data._impl as web.ChartData)),
      );

  ChartData get data => ChartData._((_impl as web.ChartConfiguration).data);

  set data(ChartData value) {
    (_impl as web.ChartConfiguration).data = (value._impl as web.ChartData);
  }

  String get type => (_impl as web.ChartConfiguration).type;

  set type(String value) {
    (_impl as web.ChartConfiguration).type = value;
  }
}

final class ChartData {
  ChartData._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  /// Creates a JavaScript object literal with these properties.
  factory ChartData({
    List<String>? labels,
    required List<ChartDataset> datasets,
  }) => ChartData._(
    web.ChartData(
      labels: _n(labels, (v0) => [for (final e0 in v0) e0.toJS].toJS),
      datasets: [for (final e0 in datasets) (e0._impl as web.ChartDataset)]
          .toJS,
    ),
  );

  List<ChartDataset> get datasets => [
    for (final e0 in (_impl as web.ChartData).datasets.toDart)
      ChartDataset._(e0),
  ];

  set datasets(List<ChartDataset> value) {
    (_impl as web.ChartData).datasets = [
      for (final e0 in value) (e0._impl as web.ChartDataset),
    ].toJS;
  }

  List<String>? get labels => _n(
    (_impl as web.ChartData).labels,
    (v0) => [for (final e0 in v0.toDart) e0.toDart],
  );

  set labels(List<String>? value) {
    (_impl as web.ChartData).labels = _n(
      value,
      (v0) => [for (final e0 in v0) e0.toJS].toJS,
    );
  }
}

final class ChartDataset {
  ChartDataset._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  /// Creates a JavaScript object literal with these properties.
  factory ChartDataset({String? label, required List<num> data}) =>
      ChartDataset._(
        web.ChartDataset(
          label: label,
          data: [for (final e0 in data) e0.toJS].toJS,
        ),
      );

  List<num> get data => [
    for (final e0 in (_impl as web.ChartDataset).data.toDart) e0.toDartDouble,
  ];

  set data(List<num> value) {
    (_impl as web.ChartDataset).data = [for (final e0 in value) e0.toJS].toJS;
  }

  String? get label => (_impl as web.ChartDataset).label;

  set label(String? value) {
    (_impl as web.ChartDataset).label = value;
  }
}

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);
