// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'package:bindsmith_runtime/bindsmith_runtime.dart';
import 'package:objective_c/objective_c.dart';

import 'src/generated/ios/swift.g.dart' as ios;
import 'src/generated/macos/swift.g.dart' as macos;

/// Mixes volumes. The array parameter is what swift2objc drops.
final class MixerWrapper {
  MixerWrapper._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  factory MixerWrapper() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => MixerWrapper._(ios.MixerWrapper()),
    BindsmithPlatform.macos => MixerWrapper._(macos.MixerWrapper()),
    _ => throw BindsmithUnsupported('MixerWrapper.new', bindsmithPlatform),
  };

  static MixerWrapper alloc() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => MixerWrapper._(ios.MixerWrapper.alloc()),
    BindsmithPlatform.macos => MixerWrapper._(macos.MixerWrapper.alloc()),
    _ => throw BindsmithUnsupported('MixerWrapper.alloc', bindsmithPlatform),
  };

  MixerWrapper init() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => MixerWrapper._((_impl as ios.MixerWrapper).init()),
    BindsmithPlatform.macos => MixerWrapper._(
      (_impl as macos.MixerWrapper).init(),
    ),
    _ => throw BindsmithUnsupported('MixerWrapper.init', bindsmithPlatform),
  };
}

/// A playback level. A struct, so swift2objc cannot represent it as-is.
final class VolumeWrapper {
  VolumeWrapper._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  static VolumeWrapper alloc() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => VolumeWrapper._(ios.VolumeWrapper.alloc()),
    BindsmithPlatform.macos => VolumeWrapper._(macos.VolumeWrapper.alloc()),
    _ => throw BindsmithUnsupported('VolumeWrapper.alloc', bindsmithPlatform),
  };

  VolumeWrapper initWithLevel(int level) => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => VolumeWrapper._(
      (_impl as ios.VolumeWrapper).initWithLevel(level),
    ),
    BindsmithPlatform.macos => VolumeWrapper._(
      (_impl as macos.VolumeWrapper).initWithLevel(level),
    ),
    _ => throw BindsmithUnsupported(
      'VolumeWrapper.initWithLevel',
      bindsmithPlatform,
    ),
  };

  @BindsmithVerify('ios: no marshalling for NSString; passed through unchanged')
  @BindsmithVerify(
    'macos: no marshalling for NSString; passed through unchanged',
  )
  NSString label() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => (_impl as ios.VolumeWrapper).label(),
    BindsmithPlatform.macos => (_impl as macos.VolumeWrapper).label(),
    _ => throw BindsmithUnsupported('VolumeWrapper.label', bindsmithPlatform),
  };

  int get level => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => (_impl as ios.VolumeWrapper).level,
    BindsmithPlatform.macos => (_impl as macos.VolumeWrapper).level,
    _ => throw BindsmithUnsupported('VolumeWrapper.level', bindsmithPlatform),
  };

  set level(int value) {
    switch (bindsmithPlatform) {
      case BindsmithPlatform.ios:
        (_impl as ios.VolumeWrapper).level = value;
      case BindsmithPlatform.macos:
        (_impl as macos.VolumeWrapper).level = value;
      default:
        throw BindsmithUnsupported('VolumeWrapper.level', bindsmithPlatform);
    }
  }

  /// Doubles the level.
  VolumeWrapper louder() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => VolumeWrapper._(
      (_impl as ios.VolumeWrapper).louder(),
    ),
    BindsmithPlatform.macos => VolumeWrapper._(
      (_impl as macos.VolumeWrapper).louder(),
    ),
    _ => throw BindsmithUnsupported('VolumeWrapper.louder', bindsmithPlatform),
  };
}

final class instancetype {
  instancetype._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;
}

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);

// Not emitted by the facade (see `bindsmith verify`):
//   ios MixerWrapper.allocWithZone — hidden by fixup MixerWrapper.allocWithZone
//   ios MixerWrapper.new$ — hidden by fixup MixerWrapper.new$
//   ios VolumeWrapper.allocWithZone — hidden by fixup VolumeWrapper.allocWithZone
//   macos MixerWrapper.allocWithZone — hidden by fixup MixerWrapper.allocWithZone
//   macos MixerWrapper.new$ — hidden by fixup MixerWrapper.new$
//   macos VolumeWrapper.allocWithZone — hidden by fixup VolumeWrapper.allocWithZone
