# GENERATED BY bindsmith — do not edit.
#
# jnigen looks a class up by name when Dart first calls it, which
# R8 cannot see, so every class the binding uses is kept whole.

-keep class androidx.biometric.BiometricManager { *; }
