Pod::Spec.new do |s|
  s.name             = 'swift_volume'
  s.module_name      = 'VolumeKit'
  s.version          = '0.0.1'
  s.summary          = 'Swift-only VolumeKit bindings generated by bindsmith.'
  s.description      = 'SwiftPM VolumeKit through the bindsmith wrapper path.'
  s.homepage         = 'https://github.com/listepo/bindsmith'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'bindsmith' => 'bindsmith@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'swift_volume/Sources/swift_volume/**/*.{h,m,swift}', '../lib/src/generated/macos/*.{m,h,swift}', '../native/VolumeKit/Sources/VolumeKit/*.swift'
  s.frameworks = 'Foundation'
  s.dependency 'FlutterMacOS'
  s.platform = :osx, '11.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.swift_version = '5.0'
end
