/// The Android side of a `jvm` binding (plan P3-4): what Gradle and R8 need
/// so that the classes the binding names exist at run time.
///
/// jnigen looks a class up by name the first time Dart calls it, and nothing
/// R8 can see refers to it that way. In a release build R8 therefore removes
/// or renames every bound class the Java side does not use itself, and the
/// call fails with `ClassNotFoundException` — in release only. Hence one
/// `-keep` rule per bound class, handed out as *consumer* rules of the
/// package's Android library so that they reach every app depending on it
/// without the app doing anything. The Maven dependencies the binding was
/// generated against go into the same Gradle script, because a class that is
/// kept but was never on the app's class path fails just the same.
///
/// Neither file is `android/build.gradle` itself, which belongs to the
/// package author: it applies the script once, and `ffiPlugin: true` in the
/// pubspec is what makes Flutter build that Android library at all.
library;

import 'package:path/path.dart' as p;

import '../ir/ir.dart';
import 'layout.dart';

/// [Layout.androidGradle] and [Layout.androidRules] for the Android binding
/// [ir], keyed by path.
///
/// Throws [ArgumentError] for a coordinate or repository that cannot be
/// written into a Groovy string literal.
Map<String, String> emitAndroidGlue(Layout layout, List<Decl> ir) {
  final deps = layout.config.platforms[Platform.android]!.deps;
  final gradle = StringBuffer()
    ..writeln('// GENERATED BY bindsmith — do not edit.')
    ..writeln('//')
    ..writeln(
      '// What the Android binding needs at run time. Apply it once from',
    )
    ..writeln('// android/build.gradle:')
    ..writeln('//')
    ..writeln("//     apply from: 'bindsmith.gradle'")
    ..writeln('//')
    ..writeln(
      '// (build.gradle.kts: apply(from = "bindsmith.gradle")), and let',
    )
    ..writeln('// Flutter build this Android library, in pubspec.yaml:')
    ..writeln('//')
    ..writeln('//     flutter:')
    ..writeln('//       plugin:')
    ..writeln('//         platforms:')
    ..writeln('//           android:')
    ..writeln('//             ffiPlugin: true')
    ..writeln();
  if (deps.maven.isNotEmpty) {
    gradle.writeln('repositories {');
    if (deps.repositories.isEmpty) {
      gradle.writeln('    mavenCentral()');
    }
    for (final repository in deps.repositories) {
      gradle.writeln('    maven { url ${_groovy('$repository')} }');
    }
    gradle
      ..writeln('}')
      ..writeln();
  }
  gradle
    ..writeln('android {')
    ..writeln('    defaultConfig {')
    ..writeln(
      '        // Every app using this package keeps the bound classes.',
    )
    ..writeln(
      '        consumerProguardFiles '
      '${_groovy(p.url.basename(Layout.androidRules))}',
    )
    ..writeln('    }')
    ..writeln('}');
  if (deps.maven.isNotEmpty) {
    gradle
      ..writeln()
      ..writeln('dependencies {');
    for (final coordinate in deps.maven) {
      gradle.writeln('    implementation ${_groovy('$coordinate')}');
    }
    gradle.writeln('}');
  }

  final types = ir.whereType<TypeDecl>().where((t) => !t.isDropped);
  final rules = StringBuffer()
    ..writeln('# GENERATED BY bindsmith — do not edit.')
    ..writeln('#')
    ..writeln(
      '# jnigen looks a class up by name when Dart first calls it, which',
    )
    ..writeln('# R8 cannot see, so every class the binding uses is kept whole.')
    ..writeln();
  for (final id in [for (final t in types) t.id]..sort()) {
    rules.writeln('-keep class $id { *; }');
  }
  final suspends = types.any(
    (t) => t.members.any((m) => m.async == Async.future && !m.isDropped),
  );
  if (suspends) {
    // jnigen's own kotlin_plugin example ships the same rule.
    rules
      ..writeln()
      ..writeln('# A suspend fun resumes Dart through kotlin.coroutines, which')
      ..writeln('# package:jni calls by name as well.')
      ..writeln('-keep class kotlin.coroutines.** { *; }');
  }
  return {
    Layout.androidGradle: gradle.toString(),
    Layout.androidRules: rules.toString(),
  };
}

/// [value] as a single-quoted Groovy literal, which interpolates nothing, so
/// only a quote or a backslash could break out of it.
String _groovy(String value) {
  if (value.contains(RegExp(r"['\\]"))) {
    throw ArgumentError.value(
      value,
      'deps',
      'a quote or a backslash cannot go into a generated Gradle literal',
    );
  }
  return "'$value'";
}
