/// The Apple side of an Objective-C or Swift binding (plan P2-3): what a
/// CocoaPods podspec and a SwiftPM target need so the generated `.m` glue is
/// compiled and linked.
///
/// Neither snippet is the author's podspec or `Package.swift` itself — those
/// files belong to the package author. Each emitted file says what to add
/// (`s.source_files`, `s.frameworks`, `ffiPlugin`, target `sources`,
/// `linkerSettings`) and carries the lines to merge.
///
/// [Layout.glue] is the only source for where the `.m` lives; nothing here
/// joins paths to the binding or the glue on its own.
library;

import '../ir/ir.dart';
import 'layout.dart';

/// Beside-package path for the CocoaPods snippet, relative to `bindsmith.yaml`.
String applePodspecPath(Platform platform) =>
    '${platform.name}/bindsmith.podspec.snippet';

/// Beside-package path for the SwiftPM snippet, relative to `bindsmith.yaml`.
String applePackageSwiftPath(Platform platform) =>
    '${platform.name}/bindsmith.Package.swift.snippet';

/// Extra Apple tooling [doctor] should report once P3-6 extends it (plan
/// P2-3): Xcode and swiftc are already checked; the iOS Simulator SDK path
/// is not yet. Probe with:
///
///     xcrun --show-sdk-path --sdk iphonesimulator
const appleDoctorSimulatorSdkProbe = [
  'xcrun',
  '--show-sdk-path',
  '--sdk',
  'iphonesimulator',
];

/// [applePodspecPath] and [applePackageSwiftPath] for [platform], keyed by
/// path.
///
/// Throws [ArgumentError] when [platform] is not [Platform.ios] or
/// [Platform.macos].
Map<String, String> emitAppleGlue(
  Layout layout,
  List<Decl> decls, {
  required Platform platform,
}) {
  if (platform != Platform.ios && platform != Platform.macos) {
    throw ArgumentError.value(
      platform,
      'platform',
      'only ios and macos produce Apple glue',
    );
  }
  final glue = layout.glue(platform);
  final glueFromPlatform = '../$glue';
  final frameworks = _frameworks(decls);
  final podspec = StringBuffer()
    ..writeln('# GENERATED BY bindsmith — do not edit.')
    ..writeln('#')
    ..writeln('# What the ${platform.name} binding needs at build time. Add')
    ..writeln(
      '# these lines to your podspec (${platform.name}/<plugin>.podspec),',
    )
    ..writeln('# once:')
    ..writeln('#')
    ..writeln(
      "#     s.source_files = 'Classes/**/*.{h,m}', '$glueFromPlatform'",
    )
    ..writeln("#     s.frameworks = '${frameworks.join("', '")}'")
    ..writeln('#')
    ..writeln('# The glue must be compiled — `Classes/**` is where Flutter')
    ..writeln('# plugins keep native sources. Commit the generated `.m` beside')
    ..writeln('# the Dart binding and point `source_files` at both.')
    ..writeln('#')
    ..writeln('# And let Flutter build this as an FFI plugin, in pubspec.yaml:')
    ..writeln('#')
    ..writeln('#     flutter:')
    ..writeln('#       plugin:')
    ..writeln('#         platforms:')
    ..writeln('#           ${platform.name}:')
    ..writeln('#             ffiPlugin: true')
    ..writeln()
    ..writeln("s.source_files = 'Classes/**/*.{h,m}', '$glueFromPlatform'")
    ..writeln("s.frameworks = '${frameworks.join("', '")}'");

  final swiftpm = StringBuffer()
    ..writeln('// GENERATED BY bindsmith — do not edit.')
    ..writeln('//')
    ..writeln('// What the ${platform.name} binding needs at build time. Add')
    ..writeln('// the `sources` entry and `linkerSettings` to your SwiftPM')
    ..writeln('// target in Package.swift, once:')
    ..writeln('//')
    ..writeln('//     .target(')
    ..writeln('//       name: "MyTarget",')
    ..writeln('//       dependencies: [],')
    ..writeln("//       sources: ['$glueFromPlatform'],")
    ..writeln('//       linkerSettings: [');
  for (final framework in frameworks) {
    swiftpm.writeln('//         .linkedFramework("$framework"),');
  }
  swiftpm
    ..writeln('//       ]')
    ..writeln('//     )')
    ..writeln('//')
    ..writeln('// Commit the generated `.m` beside the Dart binding.')
    ..writeln('sources: [')
    ..writeln("  '$glueFromPlatform',")
    ..writeln(']')
    ..writeln('linkerSettings: [');
  for (final framework in frameworks) {
    swiftpm.writeln('  .linkedFramework("$framework"),');
  }
  swiftpm.writeln(']');

  return {
    applePodspecPath(platform): podspec.toString(),
    applePackageSwiftPath(platform): swiftpm.toString(),
  };
}

/// Frameworks the binding needs at link time. Every Apple binding pulls in
/// Foundation; nothing else is inferred yet.
List<String> _frameworks(List<Decl> _) => const ['Foundation'];
