/// `hook/build.dart` for the platforms that configured `build:` (plan P1-3,
/// P5-5).
///
/// A Dart package has exactly one build hook and it runs once per target, so
/// the file is one guard per platform rather than one file per platform. Each
/// guard declares the code asset that platform's binding already names in its
/// `@DefaultAsset`, which is the whole point of routing both through [Layout]:
/// a binding whose asset id no vendor declares fails at the first call with
/// nothing to point at.
///
/// Two toolchains are supported, matching the `hook:` key. `native_toolchain_c`
/// compiles the listed sources directly and is the shape the `package_ffi`
/// template uses. `native_toolchain_cmake` runs an existing `CMakeLists.txt`,
/// installs into the hook's own output directory and picks the built library
/// up from there, because CMake decides the file name itself.
library;

import 'package:dart_style/dart_style.dart';

import '../config/config.dart';
import '../ir/ir.dart';
import 'layout.dart';

/// The `OS` constant of `package:code_assets` for each platform bindsmith
/// knows. Web has no native build, so it has no entry.
const _os = {
  Platform.android: 'OS.android',
  Platform.ios: 'OS.iOS',
  Platform.macos: 'OS.macOS',
  Platform.windows: 'OS.windows',
  Platform.linux: 'OS.linux',
};

/// The build hook for [layout], or `null` when no platform configured `build:`.
///
/// Throws [ArgumentError] for a `build:` that cannot be carried out, rather
/// than writing a hook that fails later on someone else's machine.
String? emitBuildHook(Layout layout) {
  final builds = layout.builds;
  if (builds.isEmpty) return null;
  final uses = builds.values.map((build) => build.hook).toSet();
  final b = StringBuffer()
    ..writeln('// GENERATED BY bindsmith — do not edit.')
    ..writeln()
    ..writeln("import 'package:code_assets/code_assets.dart';")
    ..writeln("import 'package:hooks/hooks.dart';");
  if (uses.contains(BuildHook.c)) {
    b.writeln("import 'package:native_toolchain_c/native_toolchain_c.dart';");
  }
  if (uses.contains(BuildHook.cmake)) {
    b.writeln(
      "import 'package:native_toolchain_cmake/native_toolchain_cmake.dart';",
    );
  }
  b
    ..writeln()
    ..writeln('void main(List<String> args) async {')
    ..writeln('  await build(args, (input, output) async {');
  for (final MapEntry(key: platform, value: build) in builds.entries) {
    final os = _os[platform];
    if (os == null) {
      throw ArgumentError.value(
        platform.name,
        'build',
        'has no native build: remove "build:" from this platform',
      );
    }
    b
      ..writeln('    // ${platform.name}')
      ..writeln('    if (input.config.code.targetOS == $os) {')
      ..write(switch (build.hook) {
        BuildHook.c => _c(layout, platform, build),
        BuildHook.cmake => _cmake(layout, platform, build),
      })
      ..writeln('    }');
  }
  b
    ..writeln('  });')
    ..writeln('}');
  return DartFormatter(languageVersion: DartFormatter.latestLanguageVersion)
      .format(b.toString());
}

String _c(Layout layout, Platform platform, BuildConfig build) {
  if (build.sources.isEmpty) {
    throw ArgumentError.value(
      build.sources,
      'sources',
      'native_toolchain_c compiles the listed sources, so it needs at '
          'least one (${platform.name})',
    );
  }
  return '''
      await CBuilder.library(
        name: '${layout.config.name}',
        assetName: '${_assetName(layout, platform)}',
        sources: [${build.sources.map(_literal).join(', ')}],
      ).run(input: input, output: output);
''';
}

String _cmake(Layout layout, Platform platform, BuildConfig build) {
  if (build.sources.length != 1) {
    throw ArgumentError.value(
      build.sources,
      'sources',
      'native_toolchain_cmake runs one CMakeLists.txt, so sources names the '
          'one directory holding it (${platform.name})',
    );
  }
  // CMake names the built file itself, so the library is installed into the
  // hook's output directory and looked up there rather than guessed at.
  return '''
      await CMakeBuilder.create(
        name: '${layout.config.name}',
        sourceDir: input.packageRoot.resolve(${_literal(build.sources.single)}),
        defines: {
          'CMAKE_INSTALL_PREFIX':
              '\${input.outputDirectory.toFilePath()}/install',
        },
        targets: ['install'],
      ).run(input: input, output: output);
      await output.findAndAddCodeAssets(
        input,
        names: {'${layout.config.name}': '${_assetName(layout, platform)}'},
        outDir: input.outputDirectory.resolve('install'),
      );
''';
}

/// The asset id without its `package:<package>/` prefix, which is what the
/// builders take.
String _assetName(Layout layout, Platform platform) =>
    layout.assetId(platform).split('/').skip(1).join('/');

String _literal(String value) {
  final path = value.replaceAll(r'\', '/');
  if (path.contains(RegExp(r"['\$\\]"))) {
    throw ArgumentError.value(
      value,
      'sources',
      r'a quote, a backslash or a $ cannot go into a generated path literal',
    );
  }
  return "'$path'";
}
