/// dart:js_interop emitter (plan P4-3): the web platform binding.
///
/// Every non-dropped [TypeDecl] becomes an extension type over `JSObject`
/// with `external` members; functions and variables become top-level
/// `external` declarations. Names that differ from the JavaScript ones are
/// bound with `@JS('...')`. Primitive facade types stay Dart primitives
/// (dart:js_interop converts them), `List<T>` becomes `JSArray<T>` and an
/// async result becomes `JSPromise<T>`; the facade converts those back.
///
/// Verify markers are written as `// verify:` comments so the binding file
/// stays free of the runtime dependency; the facade carries the annotations.
library;

import 'package:dart_style/dart_style.dart';

import '../ir/ir.dart';

const _header =
    '// GENERATED BY bindsmith — do not edit.\n'
    '// ignore_for_file: type=lint, unused_element, non_constant_identifier_names\n';

/// Emits the web binding for [decls]. [module] is the JavaScript namespace or
/// module object the declarations live on (`@JS('myLib')`); null means the
/// global scope.
String emitJsInterop(List<Decl> decls, {String? module}) {
  final b = StringBuffer(_header)
    ..writeln(module == null ? '@JS()' : '@JS(${_str(module)})')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'dart:js_interop';")
    ..writeln();
  final notEmitted = <String>[];
  for (final d in decls) {
    if (d.isDropped) {
      notEmitted.add('${d.name} — ${_reason(d.markers)}');
      continue;
    }
    switch (d) {
      case TypeDecl():
        _type(b, d, notEmitted);
      case FunctionDecl():
        _docs(b, d.docs, d.availability, d.markers);
        _paramDocs(b, d.params);
        _jsName(b, d.id, d.name, topLevel: true);
        b.writeln(
          'external ${_returnType(d.returns, d.async)} ${d.name}'
          '(${_params(d.params)});',
        );
      case VariableDecl():
        _docs(b, d.docs, d.availability, d.markers);
        _jsName(b, d.id, d.name, topLevel: true);
        b.writeln('external ${_jsType(d.type)} get ${d.name};');
        if (!d.isConst) {
          _jsName(b, d.id, d.name, topLevel: true);
          b.writeln('external set ${d.name}(${_jsType(d.type)} value);');
        }
    }
    b.writeln();
  }
  if (notEmitted.isNotEmpty) {
    b.writeln('// Not emitted (see `bindsmith verify`):');
    for (final line in notEmitted) {
      b.writeln('//   $line');
    }
  }
  return DartFormatter(languageVersion: DartFormatter.latestLanguageVersion)
      .format(b.toString());
}

void _type(StringBuffer b, TypeDecl d, List<String> notEmitted) {
  if (d.kind == TypeKind.enumeration) {
    notEmitted.add('${d.name} — enums are bound as their underlying values');
    return;
  }
  _docs(b, d.docs, d.availability, d.markers);
  b.writeln('extension type ${d.name}._(JSObject _) implements JSObject {');
  for (final m in d.members) {
    if (m.isDropped) {
      notEmitted.add('${d.name}.${m.name} — ${_reason(m.markers)}');
      continue;
    }
    _docs(b, m.docs, m.availability, m.markers);
    _paramDocs(b, m.params);
    final static = m.isStatic ? 'static ' : '';
    switch (m.kind) {
      case MemberKind.constructor:
        final name = m.name.isEmpty ? d.name : '${d.name}.${m.name}';
        final isLiteral = m.params.any((p) => p.named);
        b.writeln(
          'external ${isLiteral ? 'factory ' : ''}$name(${_params(m.params)});',
        );
      case MemberKind.method:
        _jsName(b, m.native, m.name);
        b.writeln(
          'external $static${_returnType(m.returns, m.async)} ${m.name}'
          '(${_params(m.params)});',
        );
      case MemberKind.property || MemberKind.field || MemberKind.constant:
        _jsName(b, m.native, m.name);
        b.writeln('external $static${_jsType(m.returns)} get ${m.name};');
      case MemberKind.setter:
        final param = m.params.single;
        _jsName(b, m.native, m.name);
        b.writeln(
          'external ${static}set ${m.name}(${_jsType(param.type)} '
          '${param.name});',
        );
      case MemberKind.event:
        b.writeln('// verify: event ${m.name} is not bound');
    }
  }
  b.writeln('}');
}

/// Writes the `@JS` annotation, if the declaration needs one.
///
/// A member of an extension type is interop because the extension type is, so
/// it is annotated only to rename it. A top-level member is not: `@JS()` on
/// the library supplies the namespace but does not make anything interop, and
/// without an annotation of its own the web compilers reject the `external`
/// with "Only JS interop members may be 'external'" — which `dart analyze`
/// does not report. Hence [topLevel].
void _jsName(
  StringBuffer b,
  String? native,
  String name, {
  bool topLevel = false,
}) {
  if (native != null && native != name) {
    b.writeln('@JS(${_str(native)})');
  } else if (topLevel) {
    b.writeln('@JS()');
  }
}

/// Verify comments first so the dartdoc stays attached to the declaration.
void _paramDocs(StringBuffer b, List<Param> params) {
  for (final p in params) {
    if (p.docs case final docs?) {
      b.writeln('/// - [${p.name}]: $docs');
    }
  }
}

void _docs(
  StringBuffer b,
  String? docs,
  Availability? availability,
  List<Marker> markers,
) {
  for (final m in markers) {
    if (m.kind == MarkerKind.verify) b.writeln('// verify: ${m.reason}');
  }
  if (docs != null) {
    for (final line in docs.trim().split('\n')) {
      b.writeln('/// ${line.trimRight()}'.trimRight());
    }
  }
  if (availability?.since case final since?) {
    b
      ..writeln('///')
      ..writeln('/// Available since $since.');
  }
  if (availability?.deprecated case final reason?) {
    b.writeln('@Deprecated(${_str(reason)})');
  }
}

String _reason(List<Marker> markers) => markers
    .where((m) => m.kind == MarkerKind.dropped)
    .map((m) => m.reason)
    .join('; ');

String _returnType(TypeRef returns, Async async) => switch (async) {
  Async.future => 'JSPromise<${_jsType(returns, boxed: true)}>',
  _ => _jsType(returns),
};

/// The dart:js_interop spelling of a facade type. Inside `JSArray` and
/// `JSPromise` type arguments ([boxed]) primitives must be JS types.
String _jsType(TypeRef t, {bool boxed = false}) {
  final q = t.nullability == Nullability.nullable ? '?' : '';
  TypeRef arg(int i) => i < t.args.length
      ? t.args[i]
      : const TypeRef('JSAny', nullability: Nullability.nullable);
  return switch (t.name) {
    'void' => boxed ? 'JSAny?' : 'void',
    'String' => boxed ? 'JSString$q' : 'String$q',
    'num' || 'int' || 'double' => boxed ? 'JSNumber$q' : '${t.name}$q',
    'bool' => boxed ? 'JSBoolean$q' : 'bool$q',
    'List' => 'JSArray<${_jsType(arg(0), boxed: true)}>$q',
    'Future' || 'JSPromise' => 'JSPromise<${_jsType(arg(0), boxed: true)}>$q',
    _ => '${t.name}$q',
  };
}

String _params(List<Param> params) {
  final required = <String>[];
  final optional = <String>[];
  final named = <String>[];
  for (final p in params) {
    final type = _jsType(p.type);
    if (p.named) {
      named.add(
        p.optional
            ? '${_orNullable(type)} ${p.name}'
            : 'required $type ${p.name}',
      );
    } else if (p.optional) {
      optional.add('${_orNullable(type)} ${p.name}');
    } else {
      required.add('$type ${p.name}');
    }
  }
  return [
    ...required,
    if (optional.isNotEmpty) '[${optional.join(', ')}]',
    if (named.isNotEmpty) '{${named.join(', ')}}',
  ].join(', ');
}

String _orNullable(String type) => type.endsWith('?') ? type : '$type?';

String _str(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll('\n', ' ')}'";
