/// D-Bus driver (plan P5-4).
///
/// Reads standard introspection XML and drives dart-dbus's
/// [DBusCodeGenerator] through its library API (`package:dbus/code_generator.dart`),
/// the same entry point `dart-dbus generate-remote-object` uses. The generated
/// remote-object client is the platform binding; [dbusToIr] lifts methods,
/// properties and signals into IR as a pure function of the XML.
///
/// Mapping (D-Bus introspection → IR):
///
/// | D-Bus                     | IR                                              |
/// |---------------------------|-------------------------------------------------|
/// | interface on a node       | `TypeDecl(klass)` extending `DBusRemoteObject` |
/// | method `Foo`              | `Member` `callFoo`, `async: future`, native Foo |
/// | property (read)           | `Member` `getName`, `async: future`             |
/// | property (write)          | `Member` `setName`, `async: future`             |
/// | signal `Bar`              | `Member` `bar`, `kind: event`, `async: stream`  |
/// | signature `s`, `i`, `b`…  | `String`, `int`, `bool`, … (`native` = signature) |
/// | unknown / complex signature | `DBusValue` + verify marker                   |
library;

import 'dart:io';

import 'package:dbus/code_generator.dart';
import 'package:dbus/dbus.dart';
import 'package:path/path.dart' as p;

import '../../ir/ir.dart';

const _bindsmithHeader = '// GENERATED BY bindsmith — do not edit.\n';

/// Generates a `DBusRemoteObject` client from introspection XML and returns IR.
final class DbusDriver {
  DbusDriver({required this.xmlFiles, this.classNames, this.preamble = ''});

  /// Introspection XML paths, absolute or relative to [load]'s working directory.
  final List<String> xmlFiles;

  /// Optional class name per [xmlFiles] entry (relative path key).
  final Map<String, String>? classNames;

  /// Text placed above the generated binding (after the bindsmith header line).
  final String preamble;

  /// Writes a remote-object client to [output] and returns IR for every XML file.
  Future<List<Decl>> load({
    required String workingDirectory,
    required String output,
  }) async {
    final decls = <Decl>[];
    final bodies = <String>[];
    for (final xmlFile in xmlFiles) {
      final absolute = p.canonicalize(p.join(workingDirectory, xmlFile));
      final xml = File(absolute).readAsStringSync();
      final node = parseDBusIntrospectXml(xml);
      final rel = p.relative(absolute, from: workingDirectory);
      final className = classNames?[xmlFile] ?? classNames?[rel];
      final generator = DBusCodeGenerator(node, className: className);
      decls.addAll(
        dbusToIrNode(node, sourceFile: rel, className: generator.className),
      );
      bodies.add(_stripGeneratedPreamble(generator.generateClientSource()));
    }

    final out = File(p.join(workingDirectory, output));
    out.parent.createSync(recursive: true);
    out.writeAsStringSync(_emitBinding(preamble, bodies));
    return decls;
  }
}

/// Maps introspection XML to IR. Pure.
List<Decl> dbusToIr(String xml, {String? sourceFile, String? className}) =>
    dbusToIrNode(
      parseDBusIntrospectXml(xml),
      sourceFile: sourceFile,
      className: className,
    );

/// Maps a parsed introspection node to IR. Pure.
List<Decl> dbusToIrNode(
  DBusIntrospectNode node, {
  String? sourceFile,
  String? className,
}) {
  final generator = DBusCodeGenerator(node, className: className);
  final loc = sourceFile == null ? null : SourceLoc(sourceFile);
  final interfaces = node.interfaces;
  if (interfaces.isEmpty) {
    return [
      TypeDecl(
        id: node.name ?? '<node>',
        name: generator.className,
        platform: Platform.linux,
        kind: TypeKind.opaque,
        loc: loc,
        markers: [Marker.dropped('introspection node declares no interfaces')],
      ),
    ];
  }

  final members = <Member>[];
  final declMarkers = <Marker>[];
  final usedMemberNames = <String>{
    'callMethod',
    'getAllProperties',
    'getProperty',
    'setProperty',
  };

  for (final interface in interfaces) {
    for (final method in interface.methods) {
      members.add(_methodMember(usedMemberNames, interface, method));
    }
    for (final property in interface.properties) {
      members.addAll(_propertyMembers(usedMemberNames, interface, property));
    }
    for (final signal in interface.signals) {
      members.add(_signalMember(usedMemberNames, interface, signal));
    }
  }

  final id = interfaces.length == 1
      ? interfaces.single.name
      : interfaces.map((i) => i.name).join('|');

  return [
    TypeDecl(
      id: id,
      name: generator.className,
      platform: Platform.linux,
      kind: TypeKind.klass,
      native: id,
      supertypes: const [TypeRef('DBusRemoteObject')],
      members: members,
      loc: loc,
      markers: declMarkers,
    ),
  ];
}

Member _methodMember(
  Set<String> usedNames,
  DBusIntrospectInterface interface,
  DBusIntrospectMethod method,
) {
  final notes = _DbusNotes();
  final inputArgs = method.args
      .where((arg) => arg.direction == DBusArgumentDirection.in_)
      .toList();
  final outputArgs = method.args
      .where((arg) => arg.direction == DBusArgumentDirection.out)
      .toList();
  final params = <Param>[];
  for (var i = 0; i < inputArgs.length; i++) {
    final arg = inputArgs[i];
    final mapped = _signatureType(arg.type, notes);
    params.add(Param(arg.name ?? 'arg_$i', mapped.type));
  }

  final isNoReply = _booleanAnnotation(
    method.annotations,
    'org.freedesktop.DBus.Method.NoReply',
  );
  TypeRef returns;
  if (isNoReply || outputArgs.isEmpty) {
    returns = TypeRef.void_;
  } else if (outputArgs.length == 1) {
    returns = _signatureType(outputArgs.first.type, notes).type;
  } else {
    notes.verify(
      'method ${interface.name}.${method.name} returns ${outputArgs.length} '
      'values; bound as List<DBusValue>',
    );
    returns = const TypeRef('List', args: [TypeRef('DBusValue')]);
  }

  final dartName = _uniqueMemberName(usedNames, 'call${method.name}');
  return Member(
    dartName,
    kind: MemberKind.method,
    params: params,
    returns: returns,
    async: Async.future,
    native: method.name,
    docs: 'Invokes ${interface.name}.${method.name}().',
    markers: notes.markers,
  );
}

List<Member> _propertyMembers(
  Set<String> usedNames,
  DBusIntrospectInterface interface,
  DBusIntrospectProperty property,
) {
  final members = <Member>[];

  if (property.access == DBusPropertyAccess.readwrite ||
      property.access == DBusPropertyAccess.read) {
    final notes = _DbusNotes();
    final type = _signatureType(property.type, notes).type;
    members.add(
      Member(
        _uniqueMemberName(usedNames, 'get${property.name}'),
        kind: MemberKind.method,
        returns: type,
        async: Async.future,
        native: property.name,
        docs: 'Gets ${interface.name}.${property.name}.',
        markers: notes.markers,
      ),
    );
  }

  if (property.access == DBusPropertyAccess.readwrite ||
      property.access == DBusPropertyAccess.write) {
    final notes = _DbusNotes();
    final type = _signatureType(property.type, notes).type;
    members.add(
      Member(
        _uniqueMemberName(usedNames, 'set${property.name}'),
        kind: MemberKind.method,
        params: [Param('value', type)],
        returns: TypeRef.void_,
        async: Async.future,
        native: property.name,
        docs: 'Sets ${interface.name}.${property.name}.',
        markers: notes.markers,
      ),
    );
  }

  return members;
}

Member _signalMember(
  Set<String> usedNames,
  DBusIntrospectInterface interface,
  DBusIntrospectSignal signal,
) {
  final notes = _DbusNotes();
  final params = <Param>[];
  for (var i = 0; i < signal.args.length; i++) {
    final arg = signal.args[i];
    final mapped = _signatureType(arg.type, notes);
    params.add(Param(arg.name ?? 'arg_$i', mapped.type));
  }
  final dartName = _uniqueMemberName(usedNames, _lowerCamelCase(signal.name));
  notes.verify(
    'D-Bus signal ${interface.name}.${signal.name}; subscribe through the '
    'generated DBusRemoteObjectSignal stream',
  );
  return Member(
    dartName,
    kind: MemberKind.event,
    params: params,
    returns: const TypeRef('DBusRemoteObjectSignal'),
    async: Async.stream,
    native: signal.name,
    docs: 'Signal ${interface.name}.${signal.name}.',
    markers: notes.markers,
  );
}

final class _DbusNotes {
  final markers = <Marker>[];

  void verify(String reason) => markers.add(Marker.verify(reason));
}

final class _MappedType {
  const _MappedType(this.type, {this.markers = const []});

  final TypeRef type;
  final List<Marker> markers;
}

_MappedType _signatureType(DBusSignature signature, _DbusNotes notes) {
  final native = signature.value;
  final value = native;
  if (value.isEmpty) {
    return _MappedType(TypeRef.void_, markers: notes.markers);
  }
  if (value == 'y' ||
      value == 'n' ||
      value == 'q' ||
      value == 'i' ||
      value == 'u' ||
      value == 'x' ||
      value == 't') {
    return _MappedType(TypeRef('int', native: native), markers: notes.markers);
  }
  if (value == 'b') {
    return _MappedType(TypeRef('bool', native: native), markers: notes.markers);
  }
  if (value == 'd') {
    return _MappedType(
      TypeRef('double', native: native),
      markers: notes.markers,
    );
  }
  if (value == 's') {
    return _MappedType(
      TypeRef('String', native: native),
      markers: notes.markers,
    );
  }
  if (value == 'o') {
    return _MappedType(
      TypeRef('DBusObjectPath', native: native),
      markers: notes.markers,
    );
  }
  if (value == 'g') {
    return _MappedType(
      TypeRef('DBusSignature', native: native),
      markers: notes.markers,
    );
  }
  if (value == 'v') {
    return _MappedType(
      TypeRef('DBusValue', native: native),
      markers: notes.markers,
    );
  }
  if (value == 'h') {
    return _MappedType(
      TypeRef('ResourceHandle', native: native),
      markers: notes.markers,
    );
  }
  if (value.startsWith('(') && value.endsWith(')')) {
    notes.verify('D-Bus struct signature $native is bound as List<DBusValue>');
    return _MappedType(
      TypeRef('List', args: const [TypeRef('DBusValue')], native: native),
      markers: notes.markers,
    );
  }
  if (value.startsWith('a{') && value.endsWith('}')) {
    final inner = value.substring(2, value.length - 1);
    final parts = DBusSignature(inner).split();
    if (parts.length != 2) {
      notes.verify('D-Bus dict signature $native is bound as DBusValue');
      return _MappedType(
        TypeRef('DBusValue', native: native),
        markers: notes.markers,
      );
    }
    final key = _signatureType(parts[0], notes);
    final val = _signatureType(parts[1], notes);
    return _MappedType(
      TypeRef('Map', args: [key.type, val.type], native: native),
      markers: notes.markers,
    );
  }
  if (value.startsWith('a')) {
    final child = _signatureType(DBusSignature(value.substring(1)), notes);
    return _MappedType(
      TypeRef('List', args: [child.type], native: native),
      markers: notes.markers,
    );
  }
  notes.verify('unknown D-Bus signature $native is bound as DBusValue');
  return _MappedType(
    TypeRef('DBusValue', native: native),
    markers: notes.markers,
  );
}

String _uniqueMemberName(Set<String> usedNames, String name) {
  var candidate = name;
  while (!usedNames.add(candidate)) {
    candidate = '${candidate}_';
  }
  return candidate;
}

String _lowerCamelCase(String name) =>
    name.isEmpty ? name : name[0].toLowerCase() + name.substring(1);

bool _booleanAnnotation(
  List<DBusIntrospectAnnotation> annotations,
  String name, {
  bool defaultValue = false,
}) {
  for (final annotation in annotations) {
    if (annotation.name == name) {
      return annotation.value == 'true';
    }
  }
  return defaultValue;
}

String _emitBinding(String preamble, List<String> bodies) {
  final body = bodies.join('\n');
  final imports = <String>["import 'package:dbus/dbus.dart';"];
  if (body.contains('ResourceHandle')) {
    imports.insert(0, "import 'dart:io';");
  }
  return '$_bindsmithHeader'
      '// ignore_for_file: use_super_parameters\n'
      '$preamble${imports.join('\n')}\n\n$body';
}

String _stripGeneratedPreamble(String source) {
  final lines = source.split('\n');
  var index = 0;
  while (index < lines.length &&
      (lines[index].startsWith('//') || lines[index].isEmpty)) {
    index++;
  }
  while (index < lines.length && lines[index].startsWith('import ')) {
    index++;
  }
  while (index < lines.length && lines[index].isEmpty) {
    index++;
  }
  return lines.skip(index).join('\n');
}
