// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'package:bindsmith_runtime/bindsmith_runtime.dart';
import 'package:objective_c/objective_c.dart';

import 'src/generated/ios/objc.g.dart' as ios;
import 'src/generated/macos/objc.g.dart' as macos;

/// Thin AVFoundation player declared in the entry header so the ObjC
/// driver can bind it. Framework-only headers are invisible to the pull list.
final class BSMAudioPlayer {
  BSMAudioPlayer._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  factory BSMAudioPlayer() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => BSMAudioPlayer._(ios.BSMAudioPlayer()),
    BindsmithPlatform.macos => BSMAudioPlayer._(macos.BSMAudioPlayer()),
    _ => throw BindsmithUnsupported('BSMAudioPlayer.new', bindsmithPlatform),
  };

  static BSMAudioPlayer alloc() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => BSMAudioPlayer._(ios.BSMAudioPlayer.alloc()),
    BindsmithPlatform.macos => BSMAudioPlayer._(macos.BSMAudioPlayer.alloc()),
    _ => throw BindsmithUnsupported('BSMAudioPlayer.alloc', bindsmithPlatform),
  };

  @BindsmithVerify('ios: no marshalling for NSURL; passed through unchanged')
  @BindsmithVerify('macos: no marshalling for NSURL; passed through unchanged')
  static BSMAudioPlayer? playerWithURL(NSURL url) =>
      switch (bindsmithPlatform) {
        BindsmithPlatform.ios => _n(
          ios.BSMAudioPlayer.playerWithURL(url),
          BSMAudioPlayer._,
        ),
        BindsmithPlatform.macos => _n(
          macos.BSMAudioPlayer.playerWithURL(url),
          BSMAudioPlayer._,
        ),
        _ => throw BindsmithUnsupported(
          'BSMAudioPlayer.playerWithURL',
          bindsmithPlatform,
        ),
      };

  double get duration => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => (_impl as ios.BSMAudioPlayer).duration,
    BindsmithPlatform.macos => (_impl as macos.BSMAudioPlayer).duration,
    _ => throw BindsmithUnsupported(
      'BSMAudioPlayer.duration',
      bindsmithPlatform,
    ),
  };

  BSMAudioPlayer init() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => BSMAudioPlayer._(
      (_impl as ios.BSMAudioPlayer).init(),
    ),
    BindsmithPlatform.macos => BSMAudioPlayer._(
      (_impl as macos.BSMAudioPlayer).init(),
    ),
    _ => throw BindsmithUnsupported('BSMAudioPlayer.init', bindsmithPlatform),
  };

  bool play() => switch (bindsmithPlatform) {
    BindsmithPlatform.ios => (_impl as ios.BSMAudioPlayer).play(),
    BindsmithPlatform.macos => (_impl as macos.BSMAudioPlayer).play(),
    _ => throw BindsmithUnsupported('BSMAudioPlayer.play', bindsmithPlatform),
  };

  void stop() {
    switch (bindsmithPlatform) {
      case BindsmithPlatform.ios:
        (_impl as ios.BSMAudioPlayer).stop();
      case BindsmithPlatform.macos:
        (_impl as macos.BSMAudioPlayer).stop();
      default:
        throw BindsmithUnsupported('BSMAudioPlayer.stop', bindsmithPlatform);
    }
  }
}

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);

// Not emitted by the facade (see `bindsmith verify`):
//   ios BSMAudioPlayer.allocWithZone — hidden by fixup BSMAudioPlayer.allocWithZone
//   ios BSMAudioPlayer.new$ — hidden by fixup BSMAudioPlayer.new$
//   ios instancetype — not in include list
//   macos BSMAudioPlayer.allocWithZone — hidden by fixup BSMAudioPlayer.allocWithZone
//   macos BSMAudioPlayer.new$ — hidden by fixup BSMAudioPlayer.new$
//   macos instancetype — not in include list
