// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'package:bindsmith_runtime/bindsmith_runtime.dart';

import 'src/generated/windows/winmd.g.dart' as windows;

/// To learn more, see <https://learn.microsoft.com/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount64>.
int GetTickCount64() => windows.GetTickCount64();

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);
