/// The parts of the ffigen adapter that the C and Objective-C drivers share.
///
/// ffigen's public AST exposes names, USRs and inclusion but no types, so both
/// drivers recover signatures from the Dart that ffigen generated.
/// [cRecorder] applies the pull list and records the C-side facts the AST
/// *does* have; [FfigenReader] holds the read-back that depends only on how
/// ffigen spells things (`Dart<name>` twin typedefs, `@ffi.Native<T>`
/// annotations, doc comments).
library;

import 'dart:io';

import 'package:analyzer/dart/ast/ast.dart';
import 'package:ffigen/ffigen.dart' as ffigen;
import 'package:logging/logging.dart';

import '../../ir/ir.dart';

/// First line of every binding bindsmith writes.
const bindsmithHeader = '// GENERATED BY bindsmith — do not edit.\n';

/// Every comment in a header documents, not only Doxygen's `///` and `/** */`:
/// plenty of C libraries write theirs with `//` and `/* */`. clang still pins
/// a comment to the declaration it sits against, and one after code on the
/// same line to that line's declaration.
const sourceComments = ffigen.CommentType(
  ffigen.CommentStyle.any,
  ffigen.CommentLength.full,
);

/// What ffigen knows about a C symbol beyond the Dart it generates, keyed by
/// the Dart name in the readers below.
final class CSymbol {
  const CSymbol(this.cName, {this.children = const {}, this.variadic = false});

  final String cName;

  /// Dart name → C name of fields, enum constants.
  final Map<String, String> children;
  final bool variadic;
}

/// Applies [pull] to every C declaration and records its C-side facts [into],
/// keyed by the Dart name ffigen will emit for it.
///
/// ffigen defaults every declaration to excluded, so this visitor is what
/// makes a binding non-empty. It is used unchanged by the Objective-C driver:
/// an Objective-C header still declares enums, typedefs and functions.
ffigen.Visitor cRecorder(
  bool Function(String cName) pull,
  Map<String, CSymbol> into,
) => ffigen.Visitor(
  func: (f) {
    f.isIncluded = pull(f.originalName);
    into[f.name] = CSymbol(f.originalName, variadic: f.isVariadic);
  },
  struct: (s) {
    s.isIncluded = pull(s.originalName);
    into[s.name] = CSymbol(
      s.originalName,
      children: {for (final m in s.members) m.name: m.originalName},
    );
  },
  union: (u) {
    u.isIncluded = pull(u.originalName);
    into[u.name] = CSymbol(
      u.originalName,
      children: {for (final m in u.members) m.name: m.originalName},
    );
  },
  enumClass: (e) {
    e.isIncluded = pull(e.originalName);
    // The caveat becomes a verify marker on the IR instead of a log line.
    e.silenceWarning = true;
    into[e.name] = CSymbol(
      e.originalName,
      children: {for (final c in e.constants) c.name: c.originalName},
    );
  },
  global: (g) {
    g.isIncluded = pull(g.originalName);
    into[g.name] = CSymbol(g.originalName);
  },
  macroConstant: (m) {
    m.isIncluded = pull(m.originalName);
    into[m.name] = CSymbol(m.originalName);
  },
  typealias: (t) {
    // `ifUsed`: a typedef is bound when something bound refers to it.
    t.isIncluded = pull(t.originalName)
        ? ffigen.TypealiasInclude.ifUsed
        : ffigen.TypealiasInclude.never;
    // ffigen synthesises `<name>Function` aliases without a clang USR.
    if (t.usr.startsWith('c:')) into[t.name] = CSymbol(t.originalName);
  },
);

/// Sends ffigen's warnings to stderr, which is where a CLI user expects them.
Logger stderrFfigenLogger() {
  final logger = Logger.detached('bindsmith.ffigen')..level = Level.WARNING;
  logger.onRecord.listen((r) => stderr.writeln('ffigen: ${r.message}'));
  return logger;
}

/// Read-back of an ffigen-generated binding, shared by the C and Objective-C
/// readers. Pure: it only walks a parsed [CompilationUnit].
abstract base class FfigenReader {
  FfigenReader(this.unit, this.platform, this.loc) {
    for (final d in unit.declarations) {
      if (d is GenericTypeAlias) aliases[d.name.lexeme] = d;
    }
  }

  final CompilationUnit unit;
  final Platform platform;
  final SourceLoc? loc;

  /// Every top-level typedef, including ffigen's `Dart<name>` twins.
  final aliases = <String, GenericTypeAlias>{};

  /// A written Dart type → `TypeRef`. Import prefixes are dropped: the IR
  /// names Dart types, [TypeRef.native] keeps the dart:ffi or native spelling.
  ///
  /// ffigen pairs a native typedef with a Dart-side twin (`NSInteger` /
  /// `DartNSInteger`); a twin resolves to what it aliases, with the native
  /// typedef recorded as [TypeRef.native].
  TypeRef type(TypeAnnotation t, {String? native}) {
    if (t is! NamedType) {
      // Function types only occur inside ffigen's own typedefs.
      return TypeRef(t.toSource(), native: native);
    }
    final name = t.name.lexeme;
    final alias = t.importPrefix == null ? aliases[name] : null;
    if (alias != null && name.startsWith('Dart')) {
      final c = name.substring(4);
      return type(
        alias.type,
        native: native ?? (aliases.containsKey(c) ? c : null),
      );
    }
    return TypeRef(
      name,
      args: [
        for (final a in t.typeArguments?.arguments ?? const <TypeAnnotation>[])
          type(a),
      ],
      nullability: t.question == null
          ? Nullability.nonNull
          : Nullability.nullable,
      native: native,
    );
  }

  /// The type argument of `@ffi.Native<T>()`, if present.
  TypeAnnotation? nativeType(List<Annotation> metadata) {
    for (final a in metadata) {
      if (a.name.name.endsWith('Native')) {
        return a.typeArguments?.arguments.firstOrNull;
      }
    }
    return null;
  }

  String? docs(AnnotatedNode n) {
    final tokens = n.documentationComment?.tokens;
    if (tokens == null) return null;
    return join([
      for (final t in tokens) t.lexeme.replaceFirst(RegExp(r'^///\s?'), ''),
    ]);
  }

  String? join(List<String?> parts) {
    final text = parts.nonNulls.join('\n');
    return text.isEmpty ? null : text;
  }
}

/// Splits Doxygen/Javadoc-style `@param` / `\param` lines out of [docs].
///
/// [paramNames] names the parameters the declaration actually has. A tag for
/// any other name — including a dotted name like `options.tone` — stays in
/// [memberDocs]. `@return` / `@returns` become a `Returns …` paragraph in
/// [memberDocs].
({String? memberDocs, Map<String, String> paramDocs}) splitCommentDocs(
  String? docs, {
  required Set<String> paramNames,
}) {
  if (docs == null || docs.isEmpty) {
    return (memberDocs: docs, paramDocs: const {});
  }
  final paramDocs = <String, String>{};
  final kept = <String>[];
  final paramLine = RegExp(
    r'^\\?@param(?:\s+\{[^}]+\})?\s+'
    r'(?:\[(in|out|in,out)\]\s+)?'
    r'(\w+)\s+(.*)$',
    caseSensitive: false,
  );
  final returnsLine = RegExp(r'^\\?@returns?\s+(.*)$', caseSensitive: false);
  for (final line in docs.split('\n')) {
    final trimmed = line.trimRight();
    if (paramLine.matchAsPrefix(trimmed) case final m?) {
      final name = m.group(2)!;
      if (!name.contains('.') && paramNames.contains(name)) {
        final prefix = switch (m.group(1)) {
          'out' || 'in,out' => '(out) ',
          'in' => '(in) ',
          _ => '',
        };
        paramDocs[name] = '$prefix${m.group(3)!.trim()}';
        continue;
      }
    }
    if (returnsLine.matchAsPrefix(trimmed) case final m?) {
      kept.add('Returns ${m.group(1)!.trim()}');
      continue;
    }
    kept.add(trimmed);
  }
  final member = kept.join('\n').trim();
  return (memberDocs: member.isEmpty ? null : member, paramDocs: paramDocs);
}

List<Param> withParamDocs(List<Param> params, Map<String, String> docs) => [
  for (final p in params)
    if (docs[p.name] case final d?)
      Param(p.name, p.type, optional: p.optional, named: p.named, docs: d)
    else
      p,
];
