Pod::Spec.new do |s|
  s.name             = 'avfoundation_audio'
  s.version          = '0.0.1'
  s.summary          = 'AVFoundation audio bindings generated by bindsmith.'
  s.description      = 'AVFoundation via the bindsmith ObjC driver.'
  s.homepage         = 'https://github.com/listepo/bindsmith'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'bindsmith' => 'bindsmith@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'avfoundation_audio/Sources/avfoundation_audio/**/*.{h,m,swift}', '../lib/src/generated/macos/*.{m,h}', '../src/*.{h,m}'
  s.frameworks = 'Foundation', 'AVFoundation'
  s.dependency 'FlutterMacOS'
  s.platform = :osx, '11.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end
