/// End-to-end for the C pipeline: `fixtures/c/geometry/geometry.h` → ffigen 22
/// (library API) → dart:ffi binding + IR. The binding is committed under
/// `fixtures/lib/generated/geometry/` where `dart analyze --fatal-infos
/// fixtures` proves it compiles; the IR is snapshotted under
/// `test/drivers/goldens/`. Needs libclang (Xcode, libclang-dev or LLVM).
library;

import 'dart:convert';
import 'dart:io';

import 'package:bindsmith/bindsmith.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../golden.dart';

const _fixture = 'fixtures/c/geometry/geometry.h';
const _generated = '../../fixtures/lib/generated/geometry/c.g.dart';

// packages/bindsmith → repository root.
final _root = p.dirname(p.dirname(Directory.current.path));
final _quiet = Logger.detached('quiet')..level = Level.OFF;

Future<(List<Decl>, String)> _run({bool Function(String)? include}) async {
  final tmp = Directory.systemTemp.createTempSync('bindsmith_c_');
  addTearDown(() => tmp.deleteSync(recursive: true));
  final out = p.join(tmp.path, 'c.g.dart');
  final ir = await CDriver(
    platform: Platform.linux,
    headers: [_fixture],
    include: include,
    assetId: 'package:geometry/geometry.dart',
  ).load(workingDirectory: _root, output: out, logger: _quiet);
  return (ir, File(out).readAsStringSync());
}

void main() {
  late List<Decl> ir;
  late String binding;

  setUpAll(() async => (ir, binding) = await _run());

  TypeDecl type(String name) =>
      ir.whereType<TypeDecl>().singleWhere((d) => d.name == name);
  FunctionDecl function(String name) =>
      ir.whereType<FunctionDecl>().singleWhere((d) => d.name == name);
  VariableDecl variable(String name) =>
      ir.whereType<VariableDecl>().singleWhere((d) => d.name == name);

  test('IR snapshot', () {
    final json = const JsonEncoder.withIndent('  ').convert(irToJson(ir));
    expectGolden('test/drivers/goldens/geometry.ir.json', '$json\n');
  });

  test('generated dart:ffi binding matches the committed fixture', () {
    expect(binding, startsWith('// GENERATED BY bindsmith — do not edit.\n'));
    expectGolden(_generated, binding);
  });

  test('functions carry Dart types with the dart:ffi spelling as native', () {
    final distance = function('geometry_distance');
    expect(distance.id, 'geometry_distance');
    expect(distance.loc?.file, _fixture);
    expect(distance.docs, 'Euclidean distance between two points.');
    expect(distance.returns, const TypeRef('double', native: 'ffi.Double'));
    expect(distance.params.map((q) => q.name), ['a', 'b']);
    expect(distance.params.first.type, const TypeRef('Point', native: 'Point'));

    final area = function('geometry_rect_area');
    expect(area.params.single.type.name, 'Pointer');
    expect(area.params.single.type.args.single.name, 'Rect');
    expect(area.params.single.type.native, 'ffi.Pointer<Rect>');

    final name = function('geometry_shape_name');
    expect(name.returns.name, 'Pointer');
    expect(name.returns.args.single.name, 'Char');
    expect(name.returns.native, 'ffi.Pointer<ffi.Char>');
  });

  test('enum-taking wrappers keep the enum type and the native signature', () {
    final add = function('geometry_scene_add');
    expect(add.params[0].docs, 'The scene to add to.');
    expect(add.params[1].docs, 'The shape to add.');
    expect(add.params[2].docs, 'Where to place it.');
    expect(add.docs, contains('Returns The new shape id.'));
    expect(add.params.map((q) => q.type.name), ['Pointer', 'Shape', 'Point']);
    expect(add.params[1].type.native, 'ffi.UnsignedInt');
    // `Dartgeometry_id` is resolved to its Dart type; native is the typedef.
    expect(add.returns, const TypeRef('int', native: 'geometry_id'));
    expect(
      ir.map((d) => d.name),
      isNot(anyElement(startsWith('_'))),
      reason: 'private externals behind wrappers are implementation detail',
    );
  });

  test('variadic functions are bound with fixed arguments and flagged', () {
    final log = function('geometry_log');
    expect(log.params, hasLength(1));
    expect(log.markers.single.kind, MarkerKind.verify);
    expect(log.markers.single.reason, startsWith('variadic'));
  });

  test('structs, opaque handles and enums', () {
    final point = type('Point');
    expect(point.kind, TypeKind.struct);
    expect(point.docs, 'A point in the plane.');
    expect(point.members.map((m) => m.name), ['x', 'y']);
    expect(point.members.first.kind, MemberKind.field);
    expect(
      point.members.first.returns,
      const TypeRef('double', native: 'ffi.Double'),
    );

    final rect = type('Rect');
    expect(rect.members.first.returns, const TypeRef('Point'));
    expect(rect.members.map((m) => m.name), ['origin', 'width', 'height']);

    final scene = type('GeometryScene');
    expect(scene.kind, TypeKind.opaque);
    expect(scene.members, isEmpty);
    expect(scene.docs, startsWith('Opaque scene handle'));

    final shape = type('Shape');
    expect(shape.kind, TypeKind.enumeration);
    expect(
      {for (final m in shape.members) m.name: m.value},
      {'SHAPE_CIRCLE': '0', 'SHAPE_SQUARE': '1', 'SHAPE_TRIANGLE': '2'},
    );
    expect(shape.members.first.kind, MemberKind.constant);
    expect(shape.markers.single.reason, contains('implementation-defined'));
    // A plain `//` comment documents too, and one after code on the same
    // line belongs to that line's constant rather than the next.
    expect(shape.members[0].docs, 'Measured by its radius.');
    expect(shape.members[1].docs, isNull);
  });

  test('macros become constants, externs become variables', () {
    final version = variable('GEOMETRY_VERSION');
    expect(version.isConst, isTrue);
    expect(version.type, const TypeRef('int'));
    expect(version.value, '102');
    expect(version.docs, 'Library version as MAJOR * 100 + MINOR.');
    expect(variable('GEOMETRY_PI').value, '3.14159');
    expect(variable('GEOMETRY_NAME').type, const TypeRef('String'));
    expect(variable('GEOMETRY_NAME').value, "'geometry'");

    final max = variable('geometry_max_shapes');
    expect(max.isConst, isFalse);
    expect(max.type, const TypeRef('int', native: 'ffi.Int32'));
    expect(max.docs, 'Number of shapes a scene can hold.');
  });

  test('typedefs keep the C name and point at their Dart type', () {
    final id = type('geometry_id');
    expect(id.kind, TypeKind.typedef);
    expect(id.supertypes.single, const TypeRef('int', native: 'ffi.Uint32'));

    final visitor = type('geometry_visitor');
    expect(visitor.supertypes.single.name, 'Pointer');
    expect(visitor.supertypes.single.args.single.name, 'NativeFunction');
    expect(visitor.docs, contains('Called once per shape'));
    expect(visitor.docs, contains('Callback signature: void Function('));
    expect(visitor.markers.single.reason, startsWith('C function pointer'));
    // ffigen's helper aliases are not API.
    expect(
      ir.map((d) => d.name),
      isNot(anyElement(anyOf(startsWith('Dart'), endsWith('Function')))),
    );
  });

  test('the whole header surface is bound in file order', () {
    expect(ir.map((d) => d.id), [
      'geometry_distance',
      'geometry_log',
      'geometry_max_shapes',
      'geometry_rect_area',
      'geometry_scale',
      'geometry_scene_add',
      'geometry_scene_count',
      'geometry_scene_each',
      'geometry_scene_free',
      'geometry_scene_new',
      'geometry_shape_name',
      'GEOMETRY_NAME',
      'GEOMETRY_PI',
      'GEOMETRY_VERSION',
      'GeometryScene',
      'Point',
      'Rect',
      'Shape',
      'geometry_id',
      'geometry_visitor',
    ]);
    expect(ir.map((d) => d.platform).toSet(), {Platform.linux});
  });

  test('a pull list binds the named symbols plus their dependencies', () async {
    final (pulled, source) = await _run(
      include: (c) => c == 'geometry_distance',
    );
    expect(pulled.map((d) => d.id), ['geometry_distance', 'Point']);
    expect(source, isNot(contains('geometry_log')));
  });

  test('cToIr is pure: reads a hand-written binding without libclang', () {
    final decls = cToIr(
      '''
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int puts(ffi.Pointer<ffi.Char> s);

final class Pair extends ffi.Union {
  @ffi.Int32()
  external int i;
  @ffi.Float()
  external double f;
}

class NotABinding {}
''',
      platform: Platform.windows,
      symbols: const {
        'Pair': CSymbol('pair_t', children: {'i': 'i', 'f': 'float_value'}),
      },
    );
    expect(decls.map((d) => d.id), ['puts', 'pair_t']);
    final puts = decls.first as FunctionDecl;
    expect(puts.params.single.type.native, 'ffi.Pointer<ffi.Char>');
    expect(puts.returns, const TypeRef('int', native: 'ffi.Int'));
    final pair = decls.last as TypeDecl;
    expect(pair.markers.single.reason, startsWith('C union'));
    expect(pair.members.last.native, 'float_value');
    expect(pair.members.first.native, isNull);
  });
}
