/// End-to-end for the JVM pipeline: `fixtures/jvm/greeter` → jnigen 1.0
/// (library API) → `package:jni` binding + IR. Both the binding and the IR are
/// snapshotted under `test/drivers/goldens/`.
///
/// jnigen needs `package:jni` to resolve, and jni declares a Flutter SDK
/// constraint this pure-Dart workspace cannot satisfy, so the driver runs in a
/// throwaway project that `flutter pub get` resolves ([JniProject]). That
/// takes the Flutter SDK and a JDK on PATH and, the first time only, network
/// access for jnigen to build its API summarizer with Gradle (cached
/// afterwards in `.dart_tool/jnigen/ApiSummarizer.jar`). Where either is
/// missing, the committed binding is read instead and every IR expectation
/// still runs against it, since `jvmToIr` is pure.
/// Every test here waits on an external toolchain, so the 30-second default
/// is not a timeout, it is a load test of the host: under a busy machine
/// `swiftc`, libclang, Gradle and a spawned `dart run` all exceed it and the
/// suite fails for a reason that has nothing to do with the code.
@Timeout(Duration(minutes: 5))
library;

import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:bindsmith/bindsmith.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../golden.dart';
import '../jvm_toolchain.dart';

const _fixture = 'fixtures/jvm/greeter';
// `package:jni` declares a Flutter SDK constraint, so the generated binding
// cannot live in the pure-Dart `fixtures` package where analysis runs. It is
// kept as a golden here; `kotlin_test.dart` is the suite that calls one.
const _generated = 'test/drivers/goldens/greeter_jvm.g.dart';

// packages/bindsmith → repository root.
final _root = p.dirname(p.dirname(Directory.current.path));

void main() {
  late List<Decl> ir;
  late String binding;
  late String? blocker;
  JniProject? project;

  Future<(List<Decl>, String)> run({List<String>? include}) =>
      project!.generate(
        classes: ['com.example.greeter'],
        sourcePath: [_fixture],
        include: include,
      );

  setUpAll(() async {
    blocker = await JniProject.blocker();
    if (blocker == null) {
      project = await JniProject.create();
      (ir, binding) = await run();
    } else {
      binding = File(_generated).readAsStringSync().replaceAll('\r\n', '\n');
      ir = jvmToIr(
        binding,
        platform: Platform.android,
        loc: const SourceLoc(_fixture),
      );
    }
  });
  tearDownAll(() => project?.delete());

  TypeDecl type(String name) =>
      ir.whereType<TypeDecl>().singleWhere((d) => d.name == name);
  Member member(TypeDecl t, String name, MemberKind kind) =>
      t.members.singleWhere((m) => m.name == name && m.kind == kind);

  test('IR snapshot', () {
    final json = const JsonEncoder.withIndent('  ').convert(irToJson(ir));
    expectGolden('test/drivers/goldens/greeter_jvm.ir.json', '$json\n');
  });

  test('generated jni binding matches the committed fixture', () {
    if (blocker case final why?) {
      markTestSkipped('jnigen did not run: $why');
      return;
    }
    expect(binding, startsWith('// GENERATED BY bindsmith — do not edit.\n'));
    expectGolden(_generated, binding);
  });

  test('classes keep the binary name as id and the Java signature', () {
    final greeter = type('Greeter');
    expect(greeter.id, 'com.example.greeter.Greeter');
    expect(greeter.kind, TypeKind.klass);
    expect(greeter.loc?.file, _fixture);
    expect(greeter.docs, contains('Greets people'));

    final greet = member(greeter, 'greet', MemberKind.method);
    expect(greet.isStatic, isFalse);
    expect(greet.params.single.name, 'name');
    expect(greet.params.single.type.name, 'JString');
    expect(greet.params.single.type.native, 'java.lang.String');
    expect(greet.returns.name, 'JString');
    expect(greet.returns.nullability, Nullability.nullable);
    expect(greet.returns.native, 'java.lang.String');
    expect(greet.params.single.docs, contains('person to greet'));

    expect(member(greeter, 'version', MemberKind.method).isStatic, isTrue);
  });

  test('generic Java types keep their type arguments', () {
    final all = member(type('Greeter'), 'greetAll', MemberKind.method);
    expect(all.returns.name, 'JList');
    expect(all.returns.args.single.name, 'JString');
    expect(all.returns.native, 'java.util.List<java.lang.String>');
    expect(all.params.single.type.native, 'java.util.List<java.lang.String>');
  });

  test('constructors are bound apart by their jnigen name', () {
    final ctors = type('Greeter').members
        .where((m) => m.kind == MemberKind.constructor)
        .toList();
    expect(ctors, hasLength(2));
    expect(ctors.every((c) => c.name.isEmpty && c.native == '<init>'), isTrue);
    expect(ctors.first.binding, isNull, reason: 'the default constructor');
    expect(ctors.first.params, isEmpty);
    expect(ctors.last.binding, r'new$1');
    expect(ctors.last.params.single.type.native, 'java.lang.String');
  });

  test('fields become a property plus a setter when writable', () {
    final greeter = type('Greeter');
    final count = member(greeter, 'count', MemberKind.property);
    expect(count.returns, const TypeRef('int', native: 'int'));
    expect(count.docs, contains('Number of greetings'));
    expect(
      member(greeter, 'count', MemberKind.setter).params.single.name,
      'value',
    );
    // `private` fields never reach the binding.
    expect(greeter.members.where((m) => m.name == 'prefix'), isEmpty);

    final constant = member(greeter, 'DEFAULT_PREFIX', MemberKind.property);
    expect(constant.isStatic, isTrue);
    expect(
      greeter.members.where((m) => m.name == 'DEFAULT_PREFIX'),
      hasLength(1),
      reason: 'a final field has no setter',
    );
  });

  test('interfaces are marked implementable from Dart', () {
    final listener = type(r'Greeter$Listener');
    expect(listener.kind, TypeKind.interface);
    expect(listener.id, r'com.example.greeter.Greeter$Listener');
    expect(listener.markers.single.kind, MarkerKind.verify);
    expect(
      listener.markers.single.reason,
      contains(r'Greeter$Listener.implement'),
    );
    expect(
      member(listener, 'onGreeting', MemberKind.method).params,
      hasLength(1),
    );
  });

  test('enums keep their constants as static properties', () {
    final volume = type(r'Greeter$Volume');
    expect(volume.kind, TypeKind.enumeration);
    expect(
      volume.members
          .where((m) => m.kind == MemberKind.property && m.isStatic)
          .map((m) => m.name),
      ['QUIET', 'NORMAL', 'LOUD'],
    );
    expect(member(volume, 'valueOf', MemberKind.method).isStatic, isTrue);
  });

  test('classes jnigen stubs out are dropped with the reason', () {
    final stub = type('Enum');
    expect(stub.id, 'java.lang.Enum');
    expect(stub.isDropped, isTrue);
    expect(stub.markers.single.reason, contains('java.lang.Enum'));
    expect(stub.members, isEmpty);
  });

  test('a pull list keeps the named classes only', () async {
    if (blocker case final why?) {
      markTestSkipped('jnigen did not run: $why');
      return;
    }
    final (pulled, _) = await run(include: ['com.example.greeter.Greeter']);
    final bound = pulled.whereType<TypeDecl>().where((d) => !d.isDropped);
    expect(bound.map((d) => d.id), ['com.example.greeter.Greeter']);
    // The listener is still referenced by greetAsync, so it becomes a stub.
    expect(
      pulled.where((d) => d.isDropped).map((d) => d.id),
      contains(r'com.example.greeter.Greeter$Listener'),
    );
  });

  test('jvmToIr is pure: reads a hand-written binding without a JDK', () {
    final decls = jvmToIr('''
import 'package:jni/jni.dart' as jni\$_;
import 'dart:core' as core\$_;

/// from: `com.example.Box`
extension type Box._(jni\$_.JObject _\$this) implements jni\$_.JObject {
  static final _class = jni\$_.JClass.forName(r'com/example/Box');

  /// The type which includes information such as the signature of this class.
  static const jni\$_.JType<Box> type = \$Box\$Type\$();

  /// from: `public void <init>()`
  factory Box() => throw 0;
}

extension Box\$\$Methods on Box {
  /// from: `public int size(java.util.Map<java.lang.String, java.lang.Integer> m)`
  core\$_.int size(jni\$_.JMap<jni\$_.JString?, jni\$_.JInteger?>? m) => throw 0;
}
''', platform: Platform.linux);
    final box = decls.single as TypeDecl;
    expect(box.id, 'com.example.Box');
    expect(box.members.map((m) => m.kind), [
      MemberKind.constructor,
      MemberKind.method,
    ]);
    final size = box.members.last;
    // The generic argument list is split on top-level commas only.
    expect(
      size.params.single.type.native,
      'java.util.Map<java.lang.String, java.lang.Integer>',
    );
    expect(size.returns, const TypeRef('int', native: 'int'));
  });

  test(
    'load throws without package:jni instead of letting jnigen exit',
    () async {
      if (await Isolate.resolvePackageUri(Uri.parse('package:jni/jni.dart'))
          case _?) {
        markTestSkipped('package:jni resolves here, so jnigen would just run');
        return;
      }
      final tmp = Directory.systemTemp.createTempSync('bindsmith_jvm_');
      addTearDown(() => tmp.deleteSync(recursive: true));
      // Were the guard missing, jnigen's `exit(1)` would end the test runner
      // itself rather than fail this test.
      await expectLater(
        JvmDriver(
          platform: Platform.android,
          classes: ['com.example.greeter'],
          sourcePath: [_fixture],
        ).load(workingDirectory: _root, output: p.join(tmp.path, 'jvm.g.dart')),
        throwsA(
          isA<StateError>().having(
            (e) => e.message,
            'message',
            contains('flutter pub get'),
          ),
        ),
      );
    },
  );
}
