/// End-to-end for the Objective-C pipeline: `fixtures/objc/counter/counter.h`
/// → ffigen 22 in Objective-C mode (library API) → `package:objective_c`
/// binding + IR. The binding is committed under
/// `fixtures/lib/generated/counter/` where `dart analyze --fatal-infos
/// fixtures` proves it compiles; the IR is snapshotted under
/// `test/drivers/goldens/`.
///
/// Generating needs Apple's toolchain: ffigen adds `-x objective-c` and the
/// `xcrun --show-sdk-path` sysroot itself, so only macOS can run it. Elsewhere
/// the committed binding is read instead and every IR expectation still runs
/// against it, since [objcToIr] is pure. Selectors are the one thing the
/// generated Dart does not spell out, so the checks that need them are macOS
/// only.
/// Every test here waits on an external toolchain, so the 30-second default
/// is not a timeout, it is a load test of the host: under a busy machine
/// `swiftc`, libclang, Gradle and a spawned `dart run` all exceed it and the
/// suite fails for a reason that has nothing to do with the code.
@Timeout(Duration(minutes: 5))
library;

import 'dart:convert';
import 'dart:io' as io;

import 'package:bindsmith/bindsmith.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../golden.dart';

const _fixture = 'fixtures/objc/counter/counter.h';
const _generated = '../../fixtures/lib/generated/counter/objc.g.dart';
const _glue = '../../fixtures/lib/generated/counter/objc.g.m';

// packages/bindsmith → repository root.
final _root = p.dirname(p.dirname(io.Directory.current.path));
final _quiet = Logger.detached('quiet')..level = Level.OFF;

Future<(List<Decl>, String, String)> _run({
  bool Function(String)? include,
}) async {
  final tmp = io.Directory.systemTemp.createTempSync('bindsmith_objc_');
  addTearDown(() => tmp.deleteSync(recursive: true));
  final out = p.join(tmp.path, 'objc.g.dart');
  final glue = p.join(tmp.path, 'objc.g.m');
  final ir =
      await ObjcDriver(
        platform: Platform.macos,
        headers: [_fixture],
        include: include,
        assetId: 'package:counter/counter.dart',
      ).load(
        workingDirectory: _root,
        output: out,
        objcOutput: glue,
        logger: _quiet,
      );
  return (
    ir,
    io.File(out).readAsStringSync(),
    io.File(glue).readAsStringSync(),
  );
}

void main() {
  late List<Decl> ir;
  late String binding;
  late String glue;
  final canGenerate = io.Platform.isMacOS;

  setUpAll(() async {
    if (canGenerate) {
      (ir, binding, glue) = await _run();
    } else {
      binding = io.File(_generated).readAsStringSync().replaceAll('\r\n', '\n');
      glue = '';
      ir = objcToIr(
        binding,
        platform: Platform.macos,
        loc: const SourceLoc(_fixture),
      );
    }
  });

  TypeDecl type(String name) =>
      ir.whereType<TypeDecl>().singleWhere((d) => d.name == name);
  Member member(TypeDecl t, String name, MemberKind kind) =>
      t.members.singleWhere((m) => m.name == name && m.kind == kind);
  void onlyOnApple() {
    if (!canGenerate) {
      markTestSkipped('ffigen needs xcrun and an Apple SDK');
    }
  }

  test('IR snapshot', () {
    final json = const JsonEncoder.withIndent('  ').convert(irToJson(ir));
    expectGolden('test/drivers/goldens/counter.ir.json', '$json\n');
  });

  test('generated objective_c binding matches the committed fixture', () {
    onlyOnApple();
    if (!canGenerate) return;
    expect(binding, startsWith('// GENERATED BY bindsmith — do not edit.\n'));
    expectGolden(_generated, binding);
  });

  test('the Objective-C glue file is written next to the binding', () {
    onlyOnApple();
    if (!canGenerate) return;
    expect(glue, contains('#import <Foundation/Foundation.h>'));
    expectGolden(_glue, glue);
  });

  test('an @interface becomes a class keyed by its Objective-C name', () {
    final counter = type('BSMCounter');
    expect(counter.id, 'BSMCounter');
    expect(counter.kind, TypeKind.klass);
    expect(counter.loc?.file, _fixture);
    expect(
      counter.docs,
      'Counts things, loudly or otherwise.\n\n'
      '`BSMCounter(Formatting)`: Formatting helpers kept out of the main interface.',
    );
    expect(counter.supertypes.map((t) => t.name), ['NSObject']);

    final increment = member(counter, 'increment', MemberKind.method);
    expect(increment.isStatic, isFalse);
    expect(increment.docs, 'Adds `amount` and returns the new value.');
    expect(increment.returns, const TypeRef('int', native: 'NSInteger'));
    expect(increment.params.single.name, 'amount');
    expect(increment.params.single.type.native, 'NSInteger');

    // A class method is static and keeps its `+` selector.
    expect(
      member(counter, 'counterWithLabel', MemberKind.method).isStatic,
      isTrue,
    );
  });

  test('selectors that differ from the Dart name are kept as native', () {
    onlyOnApple();
    if (!canGenerate) return;
    final counter = type('BSMCounter');
    expect(
      member(counter, 'increment', MemberKind.method).native,
      'increment:',
    );
    expect(
      member(counter, 'countTo', MemberKind.method).native,
      'countTo:completion:',
    );
    // `alloc` is spelled the same on both sides, so nothing is recorded.
    expect(member(counter, 'alloc', MemberKind.method).native, isNull);
    // ffigen documents an undocumented method with its selector, which
    // documents nothing.
    expect(member(counter, 'alloc', MemberKind.method).docs, isNull);
    expect(member(counter, 'label', MemberKind.setter).native, 'setLabel:');
  });

  test('a readonly property has no setter, a writable one does', () {
    final counter = type('BSMCounter');
    expect(
      member(counter, 'value', MemberKind.property).returns,
      const TypeRef('int', native: 'NSInteger'),
    );
    expect(
      counter.members.where((m) => m.name == 'value'),
      hasLength(1),
      reason: 'value is readonly',
    );
    expect(
      member(counter, 'label', MemberKind.property).returns.name,
      'NSString',
    );
    expect(
      member(counter, 'label', MemberKind.setter).params.single.type.name,
      'NSString',
    );
    // `nullable` on the ObjC side survives as a nullable Dart type.
    expect(
      member(counter, 'delegate', MemberKind.property).returns.nullability,
      Nullability.nullable,
    );
  });

  test('a block parameter is a callback and names its builder class', () {
    final countTo = member(type('BSMCounter'), 'countTo', MemberKind.method);
    expect(countTo.async, Async.callback);
    expect(countTo.params.map((q) => q.name), ['target', 'completion']);
    final handler = countTo.params.last;
    expect(handler.named, isTrue);
    expect(handler.optional, isFalse, reason: 'required named');
    expect(handler.type.name, 'ObjCBlock');
    expect(handler.type.native, 'BSMCountHandler');
    expect(
      countTo.markers.single.reason,
      allOf(
        contains('ObjCBlock_ffiVoid_NSInteger_NSError.listener'),
        contains('becomes a Future in the facade'),
      ),
    );
  });

  test('an NSError out-parameter is dropped, and that is recorded', () {
    final validate = member(type('BSMCounter'), 'validate', MemberKind.method);
    expect(validate.returns, const TypeRef('bool'));
    expect(validate.params.map((q) => q.name), ['target']);
    expect(validate.markers.single.reason, contains('throws NSErrorException'));
  });

  test('a @protocol is an interface that Dart can implement', () {
    final delegate = type('BSMCounterDelegate');
    expect(delegate.kind, TypeKind.interface);
    expect(delegate.id, 'BSMCounterDelegate');
    expect(delegate.supertypes.map((t) => t.name), ['NSObjectProtocol']);
    expect(
      delegate.markers.single.reason,
      contains(r'BSMCounterDelegate$Builder.implement'),
    );
    expect(
      member(delegate, 'counterDidTick', MemberKind.method).markers,
      isEmpty,
    );
    expect(
      member(
        delegate,
        'counterDidFinish',
        MemberKind.method,
      ).markers.single.reason,
      contains('@optional protocol method'),
    );
  });

  test('a category merges into the interface it extends', () {
    final counter = type('BSMCounter');
    expect(
      counter.docs,
      contains(
        '`BSMCounter(Formatting)`: Formatting helpers kept out of the main '
        'interface.',
      ),
    );
    final describe = member(counter, 'describeWithVolume', MemberKind.method);
    expect(describe.docs, 'Renders the value at the given volume.');
    expect(describe.params.single.type.name, 'BSMVolume');
    expect(describe.returns.name, 'NSString');
  });

  test('the C declarations of the same header come through too', () {
    final volume = type('BSMVolume');
    expect(volume.kind, TypeKind.enumeration);
    expect(volume.members.map((m) => (m.name, m.value)), [
      ('BSMVolumeQuiet', '0'),
      ('BSMVolumeNormal', '1'),
      ('BSMVolumeLoud', '2'),
    ]);
    // ffigen's own plumbing is private and stays out of the IR.
    expect(ir.where((d) => d.name.startsWith('_')), isEmpty);
  });

  test(
    'a pull list chooses classes, protocols and categories by name',
    () async {
      onlyOnApple();
      if (!canGenerate) return;
      Iterable<String> members(List<Decl> decls) => decls
          .whereType<TypeDecl>()
          .expand((d) => d.members)
          .map((m) => m.name);

      // The category is not named, so its methods are left out even though its
      // interface is bound.
      final (counterOnly, _, _) = await _run(include: (n) => n == 'BSMCounter');
      expect(members(counterOnly), isNot(contains('describeWithVolume')));
      // The delegate protocol is still bound: the `delegate` property needs it.
      expect(
        counterOnly.whereType<TypeDecl>().map((d) => d.name),
        contains('BSMCounterDelegate'),
      );

      // A category is named as `Interface(Category)`.
      final (withCategory, _, _) = await _run(
        include: (n) => n == 'BSMCounter' || n == 'BSMCounter(Formatting)',
      );
      expect(members(withCategory), contains('describeWithVolume'));
    },
  );

  test('objcToIr is pure: reads a hand-written binding without an SDK', () {
    final decls = objcToIr(
      '''
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;

/// Counts things.
extension type Box._(objc.ObjCObject object\$)
    implements objc.ObjCObject, objc.NSObject {
  /// Returns whether [obj] is an instance of [Box].
  static bool isA(objc.ObjCObject? obj) => throw 0;
}

extension Box\$Methods on Box {
  /// Adds one.
  DartNSInteger bump(DartNSInteger by) => throw 0;
}

typedef NSInteger = ffi.Long;
typedef DartNSInteger = int;
''',
      platform: Platform.ios,
      objc: {'Box': ObjcSymbol('BSMBox')..selectors['bump'] = 'bump:'},
    );
    final box = decls.whereType<TypeDecl>().single;
    expect(box.id, 'BSMBox');
    expect(box.name, 'Box');
    expect(box.platform, Platform.ios);
    // `isA` has no selector, so it is ffigen plumbing rather than API.
    expect(box.members.map((m) => m.name), ['bump']);
    final bump = box.members.single;
    expect(bump.native, 'bump:');
    expect(bump.returns, const TypeRef('int', native: 'NSInteger'));
    expect(bump.params.single.type, const TypeRef('int', native: 'NSInteger'));
  });

  test('the generated binding calls a real Objective-C library', () async {
    if (!canGenerate) {
      markTestSkipped('compiling Objective-C needs Apple toolchain');
      return;
    }
    final tmp = io.Directory.systemTemp.createTempSync('bindsmith_objc_run_');
    addTearDown(() => tmp.deleteSync(recursive: true));
    final dylib = p.join(tmp.path, 'libcounter.dylib');
    // The glue imports the header by name, not by path, so the include path
    // is what has to find it — the same way a podspec or a build hook does.
    final built = await io.Process.run('xcrun', [
      'clang',
      '-shared',
      '-fobjc-arc',
      '-framework',
      'Foundation',
      '-I',
      p.join(_root, 'fixtures/objc/counter'),
      p.join(_root, 'fixtures/objc/counter/counter.m'),
      p.join(_root, 'fixtures/lib/generated/counter/objc.g.m'),
      '-o',
      dylib,
    ]);
    expect(
      built.exitCode,
      0,
      reason: 'clang rejected the fixture:\n${built.stderr}',
    );
    final run = await io.Process.run(io.Platform.executable, [
      'run',
      'fixtures/bin/counter_objc.dart',
      dylib,
    ], workingDirectory: _root);
    expect(run.exitCode, 0, reason: '${run.stdout}\n${run.stderr}');
    expect(
      run.stdout,
      contains(
        'ok: properties, blocks, delegates, errors and categories cross',
      ),
    );
  });
}
