/// End-to-end for the Swift pipeline: `fixtures/swift/greeter/Greeter.swift`
/// → swiftgen 0.2 (library API) → `@objc` Swift wrapper + Objective-C glue +
/// `package:objective_c` binding + IR. The binding is committed under
/// `fixtures/lib/generated/greeter_swift/` where `dart analyze --fatal-infos
/// fixtures` proves it compiles; the IR is snapshotted under
/// `test/drivers/goldens/`.
///
/// Generating needs Xcode: swiftgen shells out to `swiftc` and to the Swift
/// symbol graph extractor, and ffigen then needs the SDK sysroot, so only
/// macOS can run it. Elsewhere the committed binding is read instead and the
/// IR expectations that do not depend on swiftgen's bookkeeping still run,
/// since [swiftToIr] is pure.
/// Every test here waits on an external toolchain, so the 30-second default
/// is not a timeout, it is a load test of the host: under a busy machine
/// `swiftc`, libclang, Gradle and a spawned `dart run` all exceed it and the
/// suite fails for a reason that has nothing to do with the code.
@Timeout(Duration(minutes: 5))
library;

import 'dart:convert';
import 'dart:io' as io;

import 'package:bindsmith/bindsmith.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../golden.dart';

const _fixture = 'fixtures/swift/greeter/Greeter.swift';
const _dir = '../../fixtures/lib/generated/greeter_swift';
const _generated = '$_dir/swift.g.dart';
const _module = 'GreeterKit';

// packages/bindsmith → repository root.
final _root = p.dirname(p.dirname(io.Directory.current.path));

typedef _Run = ({List<Decl> ir, String binding, String glue, String wrapper});

Future<_Run> _run({bool Function(String)? include}) async {
  final tmp = io.Directory.systemTemp.createTempSync('bindsmith_swift_');
  addTearDown(() => tmp.deleteSync(recursive: true));
  final out = p.join(tmp.path, 'swift.g.dart');
  final glue = p.join(tmp.path, 'swift.g.m');
  final wrapper = p.join(tmp.path, '$_module.g.swift');
  // swiftgen reports what it could not carry across on its logger, and the
  // driver needs those records, so the level has to stay open.
  final quiet = Logger.detached('swift')..level = Level.ALL;
  final ir =
      await SwiftDriver(
        platform: Platform.macos,
        sources: [_fixture],
        module: _module,
        // `Box<T>` is generic: swift2objc 0.3 writes a wrapper for it that does
        // not compile, so it is kept out of every run.
        include: include ?? (n) => n != 'Box',
        assetId: 'package:greeter/greeter.dart',
      ).load(
        workingDirectory: _root,
        output: out,
        objcOutput: glue,
        wrapperOutput: wrapper,
        logger: quiet,
      );
  // ffigen only writes the Objective-C glue when the binding needs it.
  String read(String path) {
    final f = io.File(path);
    return f.existsSync() ? f.readAsStringSync() : '';
  }

  return (ir: ir, binding: read(out), glue: read(glue), wrapper: read(wrapper));
}

void main() {
  late _Run run;
  final canGenerate = io.Platform.isMacOS;

  setUpAll(() async {
    if (canGenerate) {
      run = await _run();
    } else {
      final binding = io.File(_generated)
          .readAsStringSync()
          .replaceAll('\r\n', '\n');
      run = (
        ir: swiftToIr(
          binding,
          platform: Platform.macos,
          loc: const SourceLoc(_fixture),
        ),
        binding: binding,
        glue: '',
        wrapper: '',
      );
    }
  });

  TypeDecl type(String name) =>
      run.ir.whereType<TypeDecl>().singleWhere((d) => d.name == name);
  Member member(TypeDecl t, String name, MemberKind kind) =>
      t.members.singleWhere((m) => m.name == name && m.kind == kind);
  void onlyOnApple() {
    if (!canGenerate) markTestSkipped('swiftgen needs swiftc and an Apple SDK');
  }

  test('IR snapshot', () {
    onlyOnApple();
    if (!canGenerate) return;
    final json = const JsonEncoder.withIndent('  ').convert(irToJson(run.ir));
    expectGolden('test/drivers/goldens/greeter_swift.ir.json', '$json\n');
  });

  test('the three generated files match the committed fixtures', () {
    onlyOnApple();
    if (!canGenerate) return;
    expect(
      run.binding,
      startsWith('// GENERATED BY bindsmith — do not edit.\n'),
    );
    expectGolden(_generated, run.binding);
    expectGolden('$_dir/swift.g.m', run.glue);
    expectGolden('$_dir/$_module.g.swift', run.wrapper);
  });

  test('the generated Swift wrapper is what carries the API to ObjC', () {
    onlyOnApple();
    if (!canGenerate) return;
    expect(run.wrapper, contains('@objc public class GreeterWrapper'));
    expect(run.wrapper, contains('@objc public class VolumeWrapper'));
    expect(run.wrapper, contains('var wrappedInstance: Greeter'));
  });

  test('a Swift class is bound through its @objc wrapper', () {
    final greeter = type('GreeterWrapper');
    expect(greeter.kind, TypeKind.klass);
    expect(greeter.id, 'GreeterWrapper');
    expect(greeter.loc?.file, _fixture);

    // A Swift argument label becomes part of the selector, and ffigen names
    // the Dart method after it: `greet(name:)` → `-greetWithName:`.
    final greet = member(greeter, 'greetWithName', MemberKind.method);
    expect(greet.isStatic, isFalse);
    expect(greet.params.single.name, 'name');
    expect(greet.params.single.type.name, 'NSString');
    expect(greet.returns.name, 'NSString');
    expect(greet.native, canGenerate ? 'greetWithName:' : isNull);
    // …so the Swift spelling is not reported as lost.
    expect(run.ir.where((d) => d.name == 'greet'), isEmpty);

    // swift2objc writes no comments, so ffigen has only selectors to document
    // with; the Swift documentation comes from the symbol graph instead.
    if (canGenerate) {
      expect(greeter.docs, 'Greets people.');
      expect(greet.docs, 'Greets `name`.');
      expect(greet.params.single.docs, 'The person to greet.');
      expect(member(greeter, 'alloc', MemberKind.method).docs, isNull);
      expect(
        member(type('VolumeWrapper'), 'louder', MemberKind.method).docs,
        'Doubles the level.',
      );
    }
  });

  test('a Swift value type is bound the same way', () {
    final volume = type('VolumeWrapper');
    expect(
      member(volume, 'louder', MemberKind.method).returns.name,
      'VolumeWrapper',
    );
    // `Int` crosses as `NSInteger`, which ffigen resolves to `ffi.Long` in
    // the message signature; the header keeps no typedef to name it by.
    expect(
      member(volume, 'level', MemberKind.property).returns,
      const TypeRef('int'),
    );
    // `level` is `var`, so it round-trips; `count` on Greeter is read-only.
    expect(volume.members.where((m) => m.name == 'level'), hasLength(2));
    expect(
      type('GreeterWrapper').members.where((m) => m.name == 'count'),
      hasLength(1),
    );
  });

  test('a declaration swift2objc cannot parse is dropped, not lost', () {
    onlyOnApple();
    if (!canGenerate) return;
    // `greetAll(names: [String]) -> [String]` never reaches the wrapper, so
    // the symbol graph is what says how it was written.
    final greeter = type('Greeter');
    expect(greeter.id, 's:18symbolgraph_module7GreeterC');
    expect(greeter.kind, TypeKind.klass);
    expect(greeter.docs, 'Greets people.');

    final lost = member(greeter, 'greetAll', MemberKind.method);
    expect(lost.isDropped, isTrue);
    expect(
      lost.native,
      'func greetAll(names: [String], at volume: Volume) -> [String]',
    );
    expect(lost.docs, startsWith('Greets everyone in `names`, at `volume`.'));
    // The argument label is what a call site writes, so it is the name kept.
    expect(lost.params.map((q) => (q.name, q.type.name)), [
      ('names', '[String]'),
      ('at', 'Volume'),
    ]);
    expect(lost.returns.name, '[String]');
    expect(
      lost.markers.single.reason,
      contains('could not parse this declaration'),
    );
  });

  test('an async method is swiftgen\'s own completion handler', () {
    onlyOnApple();
    if (!canGenerate) return;
    // swift2objc turns `async` into a completion handler itself, so it never
    // reaches the bridge; the Objective-C driver reports it as a callback.
    final slowly = member(
      type('GreeterWrapper'),
      'greetSlowlyWithName',
      MemberKind.method,
    );
    expect(slowly.async, Async.callback);
    expect(slowly.native, 'greetSlowlyWithName:completionHandler:');
    expect(slowly.params.last.type.name, 'ObjCBlock');
  });

  test('a generic keeps its type parameters and every dropped member', () {
    onlyOnApple();
    if (!canGenerate) return;
    // `Box<T>` is kept out of the pull list because swift2objc writes a
    // wrapper for it that does not compile; it is still reported in full.
    final box = type('Box');
    expect(box.kind, TypeKind.struct);
    expect(box.typeParams, ['T']);
    expect(box.members.map((m) => (m.name, m.kind)), [
      ('value', MemberKind.property),
      ('value', MemberKind.setter),
      ('', MemberKind.constructor),
    ]);
    expect(box.members.every((m) => m.isDropped), isTrue);
  });

  test('the SDK is not bound just because the header imports it', () {
    onlyOnApple();
    if (!canGenerate) return;
    expect(
      run.ir.map((d) => d.name),
      isNot(anyElement(startsWith('NS'))),
      reason: 'Foundation reaches the header but is never pulled',
    );
  });

  test('a pull list keeps the named Swift declarations only', () async {
    onlyOnApple();
    if (!canGenerate) return;
    final pulled = await _run(include: (n) => n == 'Volume' || n == 'level');
    expect(
      pulled.ir.whereType<TypeDecl>().map((d) => d.name),
      isNot(contains('GreeterWrapper')),
    );
    expect(pulled.wrapper, isNot(contains('GreeterWrapper')));
    expect(
      member(type('VolumeWrapper'), 'level', MemberKind.property).name,
      'level',
    );
  });

  test(
    'a dropped member comes back through a generated @objc bridge',
    () async {
      onlyOnApple();
      if (!canGenerate) return;
      // What swift2objc could not carry becomes Swift that it never has to
      // read: the bridge is `@objc` as written, so it skips swift2objc and is
      // compiled straight into the module.
      final bridge = emitSwiftBridge(run.ir);
      expect(bridge.classes, {'GreeterBridge'});
      expectGolden('$_dir/$_module.bridge.g.swift', bridge.source);

      final tmp = io.Directory.systemTemp.createTempSync('bindsmith_bridge_');
      addTearDown(() => tmp.deleteSync(recursive: true));
      final ir =
          await SwiftDriver(
            platform: Platform.macos,
            sources: [_fixture],
            objcCompatibleSources: [
              'fixtures/lib/generated/greeter_swift/$_module.bridge.g.swift',
            ],
            objcCompatibleTypes: bridge.classes,
            module: _module,
            include: (n) => n != 'Box',
          ).load(
            workingDirectory: _root,
            output: p.join(tmp.path, 'swift.g.dart'),
            logger: Logger.detached('bridge')..level = Level.ALL,
          );

      final bridged = ir.whereType<TypeDecl>().singleWhere(
        (d) => d.name == 'GreeterBridge',
      );
      expect(
        bridged.members.map((m) => m.name),
        contains('greetAllWithNames'),
        reason: 'the Swift argument label joins the selector',
      );
      // …so `Greeter.greetAll` is no longer reported as lost.
      expect(ir.where((d) => d.name == 'Greeter'), isEmpty);
      // `Box` is generic, so it is still out of reach and still reported.
      expect(ir.singleWhere((d) => d.name == 'Box').isDropped, isFalse);
      expect(
        (ir.singleWhere((d) => d.name == 'Box') as TypeDecl).members.every(
          (m) => m.isDropped,
        ),
        isTrue,
      );
    },
  );

  test('swiftToIr is pure: it records drops without running swiftgen', () {
    final decls = swiftToIr(
      '''
import 'package:objective_c/objective_c.dart' as objc;

extension type BoxWrapper._(objc.ObjCObject object\$)
    implements objc.ObjCObject, objc.NSObject {}
''',
      platform: Platform.ios,
      objc: {'BoxWrapper': ObjcSymbol('BoxWrapper')},
      offered: {'Box': 's:3Box', 'shuffle': 's:3Boxs'},
      graph: parseSymbolgraph(_symbolgraph),
      // swift2objc points into the symbol graph it was reading.
      unparsed: const [
        'Exception: Malformed parameter list at symbols/2/declarationFragments',
      ],
    );
    // `Box` came back as `BoxWrapper`, so only its members are missing.
    expect(decls.map((d) => d.name), ['BoxWrapper', 'Box']);
    final box = decls.whereType<TypeDecl>().last;
    expect(box.id, 's:3Box');
    expect(box.kind, TypeKind.struct);
    expect(box.docs, 'A box of things.');
    expect(box.members.map((m) => m.name), ['shuffle', 'pick']);
    expect(box.members.every((m) => m.isDropped), isTrue);

    final shuffle = box.members.first;
    expect(shuffle.params.single.name, 'times');
    expect(shuffle.params.single.type.name, 'Int');
    expect(shuffle.returns.name, '[Int]');
    expect(
      shuffle.markers.single.reason,
      contains('nothing reached the binding'),
    );
    expect(
      box.members.last.markers.single.reason,
      contains('could not parse this declaration'),
    );
  });

  test('a declaration nothing can be pinned on is still reported', () {
    final decls = swiftToIr(
      '',
      platform: Platform.ios,
      unparsed: const ['Exception: something went wrong'],
    );
    expect(decls.single.name, 'unparsed');
    expect(decls.single.isDropped, isTrue);
    expect(
      decls.single.markers.single.reason,
      contains('something went wrong'),
    );
  });

  test('the generated binding calls a real Swift library', () async {
    if (!canGenerate) {
      markTestSkipped('building a Swift module needs Xcode');
      return;
    }
    final tmp = io.Directory.systemTemp.createTempSync('bindsmith_swift_run_');
    addTearDown(() => tmp.deleteSync(recursive: true));
    final dylib = p.join(tmp.path, 'libgreeter_swift.dylib');
    final sources = [
      p.join(_root, _fixture),
      p.join(_root, 'fixtures/lib/generated/greeter_swift/$_module.g.swift'),
      p.join(
        _root,
        'fixtures/lib/generated/greeter_swift/$_module.bridge.g.swift',
      ),
    ];
    // Two passes, because each half needs the other's output: `swiftc` writes
    // the Objective-C header the glue imports, and the glue then links into
    // the same module, so the mangled class names the binding asks for
    // (`_TtC10GreeterKit14GreeterWrapper`) resolve in one library.
    final header = await io.Process.run('xcrun', [
      'swiftc',
      '-emit-library',
      '-module-name',
      _module,
      '-emit-objc-header-path',
      p.join(tmp.path, '$_module-Swift.h'),
      '-o',
      dylib,
      ...sources,
    ]);
    expect(
      header.exitCode,
      0,
      reason: 'swiftc rejected the fixture:\n${header.stderr}',
    );
    final glue = p.join(tmp.path, 'swift.g.o');
    final compiled = await io.Process.run('xcrun', [
      'clang',
      '-c',
      '-fobjc-arc',
      '-I',
      tmp.path,
      p.join(_root, 'fixtures/lib/generated/greeter_swift/swift.g.m'),
      '-o',
      glue,
    ]);
    expect(
      compiled.exitCode,
      0,
      reason: 'clang rejected the generated glue:\n${compiled.stderr}',
    );
    final built = await io.Process.run('xcrun', [
      'swiftc',
      '-emit-library',
      '-module-name',
      _module,
      '-o',
      dylib,
      ...sources,
      glue,
    ]);
    expect(
      built.exitCode,
      0,
      reason: 'linking the module failed:\n${built.stderr}',
    );
    final run = await io.Process.run(io.Platform.executable, [
      'run',
      'fixtures/bin/greeter_swift.dart',
      dylib,
    ], workingDirectory: _root);
    expect(run.exitCode, 0, reason: '${run.stdout}\n${run.stderr}');
    expect(
      run.stdout,
      contains('ok: Swift properties, structs and async completions cross'),
    );
  });
}

/// A hand-written symbol graph, in the shape `swiftc -emit-symbol-graph`
/// writes: `struct Box` with one method that survives parsing and one that
/// does not.
const _symbolgraph = '''
{
  "symbols": [
    {
      "kind": {"identifier": "swift.struct"},
      "identifier": {"precise": "s:3Box"},
      "pathComponents": ["Box"],
      "declarationFragments": [
        {"kind": "keyword", "spelling": "struct"},
        {"kind": "text", "spelling": " "},
        {"kind": "identifier", "spelling": "Box"}
      ],
      "docComment": {"lines": [{"text": "A box of things."}]}
    },
    {
      "kind": {"identifier": "swift.method"},
      "identifier": {"precise": "s:3Boxs"},
      "pathComponents": ["Box", "shuffle(times:)"],
      "declarationFragments": [
        {"kind": "text", "spelling": "func shuffle(times: Int) -> [Int]"}
      ],
      "functionSignature": {
        "parameters": [
          {
            "name": "times",
            "declarationFragments": [
              {"kind": "identifier", "spelling": "times"},
              {"kind": "text", "spelling": ": "},
              {"kind": "typeIdentifier", "spelling": "Int"}
            ]
          }
        ],
        "returns": [
          {"kind": "text", "spelling": "["},
          {"kind": "typeIdentifier", "spelling": "Int"},
          {"kind": "text", "spelling": "]"}
        ]
      }
    },
    {
      "kind": {"identifier": "swift.method"},
      "identifier": {"precise": "s:3Boxp"},
      "pathComponents": ["Box", "pick()"],
      "declarationFragments": [
        {"kind": "text", "spelling": "func pick() -> Int"}
      ],
      "functionSignature": {
        "returns": [{"kind": "typeIdentifier", "spelling": "Int"}]
      }
    }
  ],
  "relationships": []
}
''';
