// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
export 'sdk_io.g.dart' if (dart.library.js_interop) 'sdk_web.g.dart';
