// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'dart:js_interop';

import 'package:bindsmith_runtime/bindsmith_runtime.dart';

import 'web.g.dart' as web;

/// Talks to the SDK.
@BindsmithVerify('declared as jsObject on web but as klass on android')
final class Client {
  Client._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  factory Client(String name) => Client._(web.Client(name));

  static String get version => web.Client.version;

  Future<void> connect() => (_impl as web.Client).connect().toDart;

  @BindsmithVerify(
    'signature differs: (double) -> double on web vs (int) -> int on android (facade uses android)',
  )
  int count(int n) => (_impl as web.Client).count(n);

  Future<String> fetchName() =>
      (_impl as web.Client).fetchName().toDart.then((v) => v.toDart);

  /// Greets [who].
  String greet(String? who) => (_impl as web.Client).greet(who);

  void legacy() {
    throw BindsmithUnsupported('Client.legacy', bindsmithPlatform);
  }

  Client? other(Client peer) =>
      _n((_impl as web.Client).other((peer._impl as web.Client)), Client._);

  /// Must be called on the main thread.
  void reset() {
    (_impl as web.Client).reset();
  }
}

Client createClient(String name) => Client._(web.createClient(name));

const String VERSION = '2.3.1';

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);

// Not emitted by the facade (see `bindsmith verify`):
//   web Client.legacy — not in include list
