// GENERATED BY bindsmith — do not edit.
// ignore_for_file: type=lint, unused_element, unused_import, unnecessary_cast, unnecessary_non_null_assertion
import 'package:bindsmith_runtime/bindsmith_runtime.dart';
import 'package:jni/jni.dart';
import 'package:objective_c/objective_c.dart';

import 'android.g.dart' as android;
import 'ios.g.dart' as ios;

/// Talks to the SDK.
@BindsmithVerify('declared as jsObject on web but as klass on android')
final class Client {
  Client._(this._impl);

  /// The platform binding object this facade wraps.
  final Object _impl;

  factory Client(String name) => switch (bindsmithPlatform) {
    BindsmithPlatform.android => Client._(android.Client(name.toJString())),
    BindsmithPlatform.ios => Client._(
      ios.SDKClient.alloc().initWithName_(NSString(name)),
    ),
    _ => throw BindsmithUnsupported('Client.new', bindsmithPlatform),
  };

  static String get version => switch (bindsmithPlatform) {
    BindsmithPlatform.android => android.Client.version.toDartString(
      releaseOriginal: true,
    ),
    BindsmithPlatform.ios => ios.SDKClient.version.toDartString(),
    _ => throw BindsmithUnsupported('Client.version', bindsmithPlatform),
  };

  Future<void> connect() => switch (bindsmithPlatform) {
    BindsmithPlatform.android => (_impl as android.Client).connect(),
    _ => throw BindsmithUnsupported('Client.connect', bindsmithPlatform),
  };

  @BindsmithVerify(
    'signature differs: (double) -> double on web vs (int) -> int on android (facade uses android)',
  )
  int count(int n) => switch (bindsmithPlatform) {
    BindsmithPlatform.android => (_impl as android.Client).count(n),
    BindsmithPlatform.ios => (_impl as ios.SDKClient).count_(n),
    _ => throw BindsmithUnsupported('Client.count', bindsmithPlatform),
  };

  Future<String> fetchName() =>
      throw BindsmithUnsupported('Client.fetchName', bindsmithPlatform);

  /// Greets [who].
  String greet(String? who) => switch (bindsmithPlatform) {
    BindsmithPlatform.android =>
      (_impl as android.Client)
          .greet(who?.toJString())
          .toDartString(releaseOriginal: true),
    BindsmithPlatform.ios =>
      (_impl as ios.SDKClient)
          .greetWithWho_(_n(who, NSString.new))
          .toDartString(),
    _ => throw BindsmithUnsupported('Client.greet', bindsmithPlatform),
  };

  void legacy() {
    switch (bindsmithPlatform) {
      case BindsmithPlatform.android:
        (_impl as android.Client).legacy();
      default:
        throw BindsmithUnsupported('Client.legacy', bindsmithPlatform);
    }
  }

  Client? other(Client peer) => switch (bindsmithPlatform) {
    BindsmithPlatform.android => _n(
      (_impl as android.Client).other((peer._impl as android.Client)),
      Client._,
    ),
    BindsmithPlatform.ios => _n(
      (_impl as ios.SDKClient).other_((peer._impl as ios.SDKClient)),
      Client._,
    ),
    _ => throw BindsmithUnsupported('Client.other', bindsmithPlatform),
  };

  /// Must be called on the main thread.
  void reset() {
    switch (bindsmithPlatform) {
      case BindsmithPlatform.android:
        (_impl as android.Client).reset();
      case BindsmithPlatform.ios:
        (_impl as ios.SDKClient).reset();
      default:
        throw BindsmithUnsupported('Client.reset', bindsmithPlatform);
    }
  }
}

Client createClient(String name) => switch (bindsmithPlatform) {
  BindsmithPlatform.android => Client._(android.createClient(name.toJString())),
  BindsmithPlatform.ios => Client._(ios.SDKCreateClient(NSString(name))),
  _ => throw BindsmithUnsupported('createClient', bindsmithPlatform),
};

const String VERSION = '2.3.1';

T? _n<S, T>(S? v, T Function(S) f) => v == null ? null : f(v);

// Not emitted by the facade (see `bindsmith verify`):
//   web Client.legacy — not in include list
