#!/bin/bash
#
# Print the Homebrew formula for one bindsmith release.
#
#   scripts/formula.sh <version> <sha256 of the macOS arm64 binary>
#
# A formula, not a cask: bindsmith is a CLI that lives in Homebrew's prefix.
# Change this script rather than a tap copy; the next release overwrites it.
set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 <version> <sha256-macos-arm64>" >&2
  exit 2
fi

VERSION="${1#v}"
SHA="$2"
if ! printf '%s' "$SHA" | grep -Eq '^[0-9a-f]{64}$'; then
  echo "not a sha256: $SHA" >&2
  exit 2
fi

cat <<EOF
# Generated by scripts/formula.sh in listepo/bindsmith. Do not edit the tap
# copy: the next release overwrites it. Change scripts/formula.sh instead.
class Bindsmith < Formula
  desc "One config, six Flutter platforms — Dart bindings for native APIs"
  homepage "https://github.com/listepo/bindsmith"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/listepo/bindsmith/releases/download/v#{version}/bindsmith-macos-arm64"
      sha256 "${SHA}"
    end
  end

  def install
    bin.install "bindsmith-macos-arm64" => "bindsmith"
  end

  test do
    assert_match "doctor", shell_output("#{bin}/bindsmith --help")
  end
end
EOF
