// GENERATED BY bindsmith — do not edit.

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:native_toolchain_c/native_toolchain_c.dart';

void main(List<String> args) async {
  await build(args, (input, output) async {
    // windows
    if (input.config.code.targetOS == OS.windows) {
      await CBuilder.library(
        name: 'my_sdk',
        assetName: 'src/generated/windows/c.g.dart',
        sources: ['src/shim.c', 'src/util.c'],
      ).run(input: input, output: output);
    }
    // linux
    if (input.config.code.targetOS == OS.linux) {
      await CBuilder.library(
        name: 'my_sdk',
        assetName: 'src/generated/linux/c.g.dart',
        sources: ['src/shim.c', 'src/util.c'],
      ).run(input: input, output: output);
    }
  });
}
