// GENERATED BY bindsmith — do not edit.

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:native_toolchain_cmake/native_toolchain_cmake.dart';

void main(List<String> args) async {
  await build(args, (input, output) async {
    // linux
    if (input.config.code.targetOS == OS.linux) {
      await CMakeBuilder.create(
        name: 'my_sdk',
        sourceDir: input.packageRoot.resolve('src/native'),
        defines: {
          'CMAKE_INSTALL_PREFIX':
              '${input.outputDirectory.toFilePath()}/install',
        },
        targets: ['install'],
      ).run(input: input, output: output);
      await output.findAndAddCodeAssets(
        input,
        names: {'my_sdk': 'src/generated/linux/c.g.dart'},
        outDir: input.outputDirectory.resolve('install'),
      );
    }
  });
}
