/// JVM driver: runs jnigen 1.0 through its library API and lifts the result
/// into the IR.
///
/// Like ffigen, jnigen's public AST (`ClassDecl`, `Method`, `Field`, `Param`)
/// carries names and inclusion but no types, and its visitors run *before*
/// renaming, so the Dart names are not known there. The generated Dart is the
/// source of truth instead: jnigen writes the Java binary name and the full
/// signature into a `/// from:` doc line on every declaration, which
/// [jvmToIr] reads back with `package:analyzer` (syntax only). For a member
/// with Kotlin metadata that line is the Kotlin signature
/// (`public suspend fun greetSlowly(name: kotlin.String): kotlin.String`), and
/// it is where the IR takes Kotlin's parameter names from: the Dart ones are
/// the bytecode's (`string`, `i`).
///
/// Mapping (Java / Kotlin → generated Dart → IR):
///
/// | Java / Kotlin           | IR                                               |
/// |-------------------------|--------------------------------------------------|
/// | class                   | `TypeDecl(klass)`, `id` = binary name            |
/// | interface               | `TypeDecl(interface)` + implementable marker     |
/// | enum                    | `TypeDecl(enumeration)`, constants as properties |
/// | nested class `A.B`      | one decl named `A$B` (jnigen's Dart name)        |
/// | constructor             | `Member('', constructor)`, `binding` = `new$1` … |
/// | method / static method  | `Member(method, isStatic:)`                      |
/// | field                   | `property` (+ `setter` when writable)            |
/// | unincluded dependency   | `TypeDecl` with a dropped marker (jnigen stub)   |
/// | `suspend fun f(): T`    | method, `returns` = `T`, `async: future`         |
/// | returns `Flow<T>`       | method + verify marker (`emitKotlinBridge`)      |
/// | default argument        | dropped `f$default`, read from the class file    |
/// | synthetic member        | member + dropped marker                          |
///
/// Types keep their `package:jni` spelling (`JString`, `JList<JString?>`);
/// `TypeRef.native` holds the Java or Kotlin type. The facade marshals
/// `JString` ↔ `String`.
///
/// @docImport '../../emit/kotlin_bridge.dart';
library;

import 'dart:convert';
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/token.dart' show Keyword;
import 'package:archive/archive.dart';
import 'package:jnigen/jnigen.dart' as jnigen;
import 'package:logging/logging.dart';
import 'package:package_config/package_config.dart';
import 'package:path/path.dart' as p;

import '../../ir/ir.dart';
import 'kdoc.dart';

const _header = '// GENERATED BY bindsmith — do not edit.\n';

const _flow = 'kotlinx.coroutines.flow.Flow';

/// Kotlin's synthetic carrier for a default argument: `greet(name, volume)`
/// also gets a static `greet$default(receiver, name, volume, mask, marker)`.
const _defaultSuffix = r'$default';

/// The last parameter of every synthetic constructor Kotlin writes.
const _constructorMarker = 'kotlin.jvm.internal.DefaultConstructorMarker';

/// Generates `package:jni` bindings for Java/Kotlin classes and returns their
/// IR.
final class JvmDriver {
  JvmDriver({
    required this.platform,
    required this.classes,
    this.sourcePath = const [],
    this.kotlinSources = const [],
    this.classPath = const [],
    this.include,
    this.preamble = '',
    this.summarizerCommand,
  });

  final Platform platform;

  /// Fully-qualified class or package names to bind. A package name pulls the
  /// classes in it; nested classes come with their parent.
  final List<String> classes;

  /// Directories of `.java` sources, relative to the working directory of
  /// [load]. jnigen summarizes sources with its doclet backend.
  final List<String> sourcePath;

  /// `.kt` files read by [kdocs] only. They are not passed to jnigen's
  /// `sourcePath`, whose doclet backend reads Javadoc from Java sources.
  final List<String> kotlinSources;

  /// Jars and class directories, relative to the working directory of [load].
  final List<String> classPath;

  /// Pull list by binary name (`com.example.Greeter`); `null` binds every
  /// class jnigen finds under [classes].
  final bool Function(String binaryName)? include;

  /// Text placed above jnigen's own header.
  final String preamble;

  /// How to run the API summarizer. Defaults to the jar under
  /// `<workingDirectory>/.dart_tool/jnigen` when it exists, so a summarizer
  /// built once at the workspace root is reused whatever the process
  /// directory is. When neither is available jnigen builds it with Gradle,
  /// which needs the network.
  final String? summarizerCommand;

  /// Writes the binding to [output] (relative to [workingDirectory]) and
  /// returns the IR of what it contains.
  ///
  /// Throws [StateError] when `package:jni` does not resolve from the current
  /// directory: jnigen reads its symbols out of that package and, failing to
  /// find it, exits the whole process rather than throwing.
  Future<List<Decl>> load({
    required String workingDirectory,
    required String output,
    Logger? logger,
  }) async {
    if (!await _resolves('jni')) {
      throw StateError(
        'package:jni does not resolve from ${Directory.current.path}, and '
        'jnigen exits the process without it. Add `jni` to the dependencies '
        'of the package that runs bindsmith and resolve it with '
        '`flutter pub get` (jni requires the Flutter SDK).',
      );
    }
    final out = File(p.join(workingDirectory, output));
    out.parent.createSync(recursive: true);
    Uri entry(String path) {
      final absolute = p.join(workingDirectory, path);
      return path.endsWith('.jar')
          ? Uri.file(absolute)
          : Uri.directory(absolute);
    }

    await jnigen.JniGenerator(
      input: jnigen.Input(
        sourcePath: [for (final s in sourcePath) entry(s)],
        classPath: [for (final c in classPath) entry(c)],
        classes: classes,
        workingDirectory: entry('.'),
        summarizerCommand: summarizerCommand ?? _summarizer(workingDirectory),
      ),
      output: jnigen.Output(
        dart: jnigen.DartOutput(
          path: Uri.file(out.absolute.path),
          structure: jnigen.OutputStructure.singleFile,
        ),
        preamble: preamble,
      ),
      visitors: [if (include case final include?) _Pull(include)],
    ).generate(logger: logger ?? _stderrLogger());
    // jnigen writes its own banner above the preamble, so the bindsmith header
    // goes on afterwards.
    final source = _header + out.readAsStringSync();
    out.writeAsStringSync(source);
    final kdocMap = <String, KDoc>{};
    for (final rel in kotlinSources) {
      kdocMap.addAll(
        kdocs(
          File(p.join(workingDirectory, rel)).readAsStringSync(),
          fileName: p.basename(rel),
        ),
      );
    }
    final ir = jvmToIr(
      source,
      platform: platform,
      loc: sourcePath.length == 1 ? SourceLoc(sourcePath.single) : null,
      kdocs: kdocMap,
    );
    return _withDefaults(ir, _defaults(ir, workingDirectory));
  }

  static String? _summarizer(String workingDirectory) {
    final jar = p.join(
      workingDirectory,
      '.dart_tool',
      'jnigen',
      'ApiSummarizer.jar',
    );
    return File(jar).existsSync() ? 'java -jar $jar' : null;
  }

  /// Binary name → the methods with a default argument, read out of the class
  /// files on [classPath]. jnigen's summarizer drops the synthetic
  /// `$default` carriers without a trace, so this is the only place the IR
  /// can learn that a Kotlin argument was optional.
  Map<String, List<String>> _defaults(List<Decl> ir, String workingDirectory) {
    final wanted = {
      for (final d in ir.whereType<TypeDecl>())
        if (!d.isDropped) '${d.id.replaceAll('.', '/')}.class': d.id,
    };
    final found = <String, List<String>>{};
    void read(String entry, Uint8List bytes) {
      final id = wanted.remove(entry)!;
      final List<ClassFileMethod> methods;
      try {
        methods = classFileMethods(bytes);
      } on FormatException catch (e) {
        throw FormatException('$entry on the class path: ${e.message}');
      }
      final names = [
        for (final m in methods)
          if (m.access & _staticSynthetic == _staticSynthetic &&
              m.name.endsWith(_defaultSuffix))
            m.name.substring(0, m.name.length - _defaultSuffix.length),
      ];
      if (names.isNotEmpty) found[id] = names;
    }

    for (final entry in classPath) {
      final path = p.join(workingDirectory, entry);
      if (Directory(path).existsSync()) {
        for (final name in [...wanted.keys]) {
          final file = File(p.joinAll([path, ...name.split('/')]));
          if (file.existsSync()) read(name, file.readAsBytesSync());
        }
      } else if (path.endsWith('.jar') && File(path).existsSync()) {
        final jar = ZipDecoder().decodeBytes(File(path).readAsBytesSync());
        for (final name in [...wanted.keys]) {
          if (jar.findFile(name)?.readBytes() case final bytes?) {
            read(name, bytes);
          }
        }
      }
    }
    return found;
  }
}

/// `ACC_STATIC | ACC_SYNTHETIC` (JVMS §4.6).
const _staticSynthetic = 0x0008 | 0x1000;

/// Whether [package] resolves the way jnigen looks it up (`findPackage` in
/// jnigen's `lib/src/util/find_package.dart`): through the package config
/// above the current directory first, then the one this isolate runs with.
Future<bool> _resolves(String package) async {
  if ((await findPackageConfig(Directory.current))?[package] != null) {
    return true;
  }
  final uri = await Isolate.packageConfig;
  return uri != null && (await loadPackageConfigUri(uri))[package] != null;
}

/// Applies the pull list. jnigen visits members only inside included classes.
final class _Pull extends jnigen.Visitor {
  const _Pull(this.include) : super.base();

  final bool Function(String binaryName) include;

  @override
  void visitClass(jnigen.ClassDecl c) => c.isIncluded = include(c.binaryName);
}

Logger _stderrLogger() {
  final logger = Logger.detached('bindsmith.jnigen')..level = Level.WARNING;
  logger.onRecord.listen((r) => stderr.writeln('jnigen: ${r.message}'));
  return logger;
}

/// A method as a class file declares it (JVMS §4.6).
typedef ClassFileMethod = ({int access, String name, String descriptor});

/// The method table of a class file: just enough of JVMS §4 to see the
/// synthetic members jnigen's summarizer leaves out. Names are decoded as
/// UTF-8, which the JVM's modified UTF-8 matches except for NUL and
/// characters outside the BMP.
///
/// Throws [FormatException] when [bytes] is not a class file.
List<ClassFileMethod> classFileMethods(Uint8List bytes) {
  final data = ByteData.sublistView(bytes);
  var at = 0;
  int u2() => data.getUint16((at += 2) - 2);
  int u4() => data.getUint32((at += 4) - 4);
  try {
    if (u4() != 0xCAFEBABE) {
      throw FormatException('not a class file: bad magic', bytes, 0);
    }
    at += 4; // minor_version, major_version
    final strings = <int, String>{};
    final count = u2();
    for (var i = 1; i < count; i++) {
      switch (data.getUint8(at++)) {
        case 1: // Utf8
          final length = u2();
          strings[i] = utf8.decode(
            bytes.sublist(at, at + length),
            allowMalformed: true,
          );
          at += length;
        case 7 || 8 || 16 || 19 || 20: // Class, String, MethodType, Module…
          at += 2;
        case 15: // MethodHandle
          at += 3;
        case 3 || 4 || 9 || 10 || 11 || 12 || 17 || 18: // Integer … Dynamic
          at += 4;
        case 5 || 6: // Long and Double take two slots.
          at += 8;
          i++;
        case final tag:
          throw FormatException(
            'not a class file: constant pool tag $tag',
            bytes,
            at - 1,
          );
      }
    }
    String string() {
      final index = u2();
      return strings[index] ??
          (throw FormatException(
            'not a class file: #$index is not a Utf8 constant',
            bytes,
            at - 2,
          ));
    }

    void skipAttributes() {
      for (var n = u2(); n > 0; n--) {
        at += 2; // attribute_name_index
        final length = u4();
        at += length;
      }
    }

    at += 6; // access_flags, this_class, super_class
    final interfaces = u2();
    at += 2 * interfaces;
    for (var n = u2(); n > 0; n--) {
      at += 6; // access_flags, name_index, descriptor_index
      skipAttributes();
    }
    final methods = <ClassFileMethod>[];
    for (var n = u2(); n > 0; n--) {
      methods.add((access: u2(), name: string(), descriptor: string()));
      skipAttributes();
    }
    skipAttributes(); // the class's own, so a truncated tail is caught too
    if (at > bytes.length) throw RangeError.range(at, 0, bytes.length);
    return methods;
  } on RangeError {
    throw FormatException('not a class file: truncated', bytes, at);
  }
}

/// Lifts a generated `package:jni` [binding] into IR. Pure: no I/O, no jnigen.
///
/// [defaults] maps a binary name to its methods with a default argument,
/// which the binding cannot show (see [classFileMethods]); each becomes a
/// dropped `<name>$default` member for [emitKotlinBridge] to find.
List<Decl> jvmToIr(
  String binding, {
  required Platform platform,
  SourceLoc? loc,
  Map<String, List<String>> defaults = const {},
  Map<String, KDoc> kdocs = const {},
}) => _withDefaults(
  _withKdocs(
    _Reader(
      parseString(
        content: binding,
        path: 'binding.g.dart',
        throwIfDiagnostics: false,
      ).unit,
      platform,
      loc,
    ).read(),
    kdocs,
  ),
  defaults,
);

/// Fills documentation from Kotlin sources wherever jnigen left none.
List<Decl> _withKdocs(List<Decl> ir, Map<String, KDoc> kdocs) {
  if (kdocs.isEmpty) return ir;
  return [
    for (final d in ir)
      switch (d) {
        TypeDecl() => _typeWithKdocs(d, kdocs),
        _ => d,
      },
  ];
}

TypeDecl _typeWithKdocs(TypeDecl d, Map<String, KDoc> kdocs) {
  final typeDoc = kdocs[d.id];
  return d.copyWith(
    docs: d.docs ?? typeDoc?.memberDocs,
    members: [for (final m in d.members) _memberWithKdocs(d.id, m, kdocs)],
  );
}

Member _memberWithKdocs(String typeId, Member m, Map<String, KDoc> kdocs) {
  final doc = kdocs[_kdocKey(typeId, m)];
  if (doc == null) return m;
  return m.copyWith(
    docs: m.docs ?? doc.memberDocs,
    params: [
      for (final q in m.params)
        Param(
          q.name,
          q.type,
          optional: q.optional,
          named: q.named,
          docs: q.docs ?? doc.paramDocs[q.name],
        ),
    ],
  );
}

String _kdocKey(String typeId, Member m) => switch (m.kind) {
  MemberKind.constructor || MemberKind.method =>
    '$typeId.${m.native ?? m.name}(${m.params.map((q) => q.name).join(',')})',
  _ => '$typeId.${m.native ?? m.name}',
};

List<Decl> _withDefaults(List<Decl> ir, Map<String, List<String>> defaults) => [
  for (final d in ir)
    switch (d) {
      TypeDecl(:final id) when defaults[id] != null => d.copyWith(
        members: [
          ...d.members,
          for (final name in defaults[id]!)
            Member(
              '$name$_defaultSuffix',
              kind: MemberKind.method,
              isStatic: true,
              markers: [
                Marker.dropped(
                  "Kotlin's synthetic carrier for the default arguments of "
                  '`$name`, which jnigen drops: Dart only sees the full arity. '
                  'emitKotlinBridge declares the shorter overload, or annotate '
                  '`$name` with `@JvmOverloads`',
                ),
              ],
            ),
        ],
      ),
      _ => d,
    },
];

/// The parts of a declaration jnigen writes into its `from:` doc line:
/// `static public final java.lang.String DEFAULT_PREFIX` in Java form, or
/// `public fun greet(name: kotlin.String): kotlin.String` for a member with
/// Kotlin metadata. [names] is `null` in Java form, where the bytecode has
/// none worth keeping.
typedef _Java = ({
  String name,
  String? type,
  List<String> params,
  List<String>? names,
  bool isSuspend,
  bool isSynthetic,
});

final class _Reader {
  _Reader(this.unit, this.platform, this.loc) {
    for (final d in unit.declarations) {
      switch (d) {
        case ExtensionTypeDeclaration():
          types[d.namePart.typeName.lexeme] = d;
        case ExtensionDeclaration(
          onClause: ExtensionOnClause(extendedType: NamedType(:final name)),
        ):
          members.putIfAbsent(name.lexeme, () => []).addAll(d.body.members);
        default:
      }
    }
  }

  final CompilationUnit unit;
  final Platform platform;
  final SourceLoc? loc;
  final types = <String, ExtensionTypeDeclaration>{};

  /// Dart type name → the members of its `extension <name>$$Methods on <name>`.
  final members = <String, List<ClassMember>>{};

  List<Decl> read() => [
    for (final MapEntry(key: name, value: d) in types.entries)
      if (!name.startsWith(r'$')) _type(name, d),
  ];

  TypeDecl _type(String name, ExtensionTypeDeclaration d) {
    final docs = _docs(d);
    final body = [...d.body.members, ...?members[name]];
    final isInterface = body.any(
      (m) => m is MethodDeclaration && m.name.lexeme == 'implementIn',
    );
    final isEnum = (d.implementsClause?.interfaces ?? const <NamedType>[]).any(
      (t) => _from(types[t.name.lexeme]) == 'java.lang.Enum',
    );
    // jnigen emits a stub for a class that is used but not in the pull list.
    final isStub = docs?.contains('is a stub') ?? false;
    return TypeDecl(
      id: _from(d) ?? name,
      name: name,
      platform: platform,
      kind: isEnum
          ? TypeKind.enumeration
          : isInterface
          ? TypeKind.interface
          : TypeKind.klass,
      members: isStub ? const [] : [for (final m in body) ?_member(m)],
      supertypes: [
        for (final t in d.implementsClause?.interfaces ?? const <NamedType>[])
          if (t.name.lexeme != 'JObject')
            TypeRef(t.name.lexeme, native: _from(types[t.name.lexeme])),
      ],
      loc: loc,
      docs: isStub ? null : docs,
      markers: [
        if (isStub)
          Marker.dropped(
            'not in the pull list; jnigen emitted a stub. Add ${_from(d) ?? name} '
            'to `classes` to bind it',
          ),
        if (isInterface)
          Marker.verify(
            'Java interface: implement it from Dart with '
            '$name.implement(\$$name(...))',
          ),
      ],
    );
  }

  Member? _member(ClassMember m) {
    final java = _signature(m);
    final synthetic = [
      if (java != null && java.isSynthetic)
        Marker.dropped(switch (java.params) {
          [..., 'int', _constructorMarker] =>
            "synthetic: Kotlin's carrier for a constructor's default "
                'arguments, behind a bitmask and a DefaultConstructorMarker. '
                'Annotate the constructor with `@JvmOverloads` to bind each '
                'arity instead',
          [..., _constructorMarker] =>
            'synthetic: the path Kotlin takes to a private constructor, not '
                'meant to be called',
          _ => 'synthetic: made by the compiler, not declared in the source',
        }),
    ];
    return switch (m) {
      // `factory Greeter.new$1(JString? prefix)` ← `public void <init>(…)`.
      ConstructorDeclaration(factoryKeyword: _?) when java?.name == '<init>' =>
        Member(
          '',
          kind: MemberKind.constructor,
          params: _params(m.parameters, java, _raw(m)),
          binding: m.name?.lexeme,
          native: '<init>',
          docs: _docs(m),
          markers: synthetic,
        ),
      MethodDeclaration() when _skip(m) => null,
      MethodDeclaration(isGetter: true) => Member(
        m.name.lexeme,
        kind: MemberKind.property,
        returns: _ref(m.returnType, java?.type),
        isStatic: m.isStatic,
        native: _native(m.name.lexeme, java),
        docs: _docs(m),
        markers: synthetic,
      ),
      MethodDeclaration(isSetter: true) => Member(
        m.name.lexeme,
        kind: MemberKind.setter,
        params: _params(m.parameters, java, _raw(m)),
        isStatic: m.isStatic,
        native: _native(m.name.lexeme, java),
        docs: _docs(m),
        markers: synthetic,
      ),
      MethodDeclaration() => Member(
        m.name.lexeme,
        kind: MemberKind.method,
        params: _params(m.parameters, java, _raw(m)),
        // jnigen binds a `suspend fun` as an `async` method returning
        // `Future<T>`; the IR carries `T`, as it does for a `Promise<T>`.
        returns: _ref(
          java?.isSuspend ?? false ? _awaited(m.returnType) : m.returnType,
          java?.type,
        ),
        async: java?.isSuspend ?? false ? Async.future : Async.none,
        isStatic: m.isStatic,
        native: _native(m.name.lexeme, java),
        docs: _docs(m),
        markers: [
          ...synthetic,
          if (java?.type case final type?
              when type == _flow || type.startsWith('$_flow<'))
            const Marker.verify(
              'returns a Kotlin `Flow`, which has no JNI surface: Dart gets an '
              'opaque object. emitKotlinBridge declares a method that '
              'collects it into a listener',
            ),
        ],
      ),
      _ => null,
    };
  }

  /// jnigen's own plumbing (ids, native lookups, `implementIn`) has no Java
  /// declaration behind it, so it carries no `from:` line.
  bool _skip(MethodDeclaration m) =>
      m.name.lexeme.startsWith('_') || _from(m) == null;

  /// Kotlin's parameter names win over the bytecode's, unless one is reserved
  /// in Dart (`in`, `default`), where jnigen's renamed one is the legal name.
  /// A signature whose arity differs from the Dart one (an extension
  /// receiver) says nothing reliable about any of them.
  List<Param> _params(FormalParameterList? list, _Java? java, String? rawDocs) {
    final dart = list?.parameters ?? const <FormalParameter>[];
    final from = java?.params.length == dart.length ? java : null;
    final paramDocs = _javadocParamDocs(rawDocs, from?.names);
    return [
      for (final (i, q) in dart.indexed)
        Param(
          switch (from?.names?[i]) {
            final name?
                when !(Keyword.keywords[name]?.isReservedWord ?? false) =>
              name,
            _ => q.name!.lexeme,
          },
          _ref(q.type, from?.params[i]),
          docs: from?.names != null && i < from!.names!.length
              ? paramDocs[from.names![i]]
              : null,
        ),
    ];
  }

  String? _native(String dartName, _Java? java) =>
      java == null || java.name == dartName ? null : java.name;

  /// `Future<JString>` → `JString`.
  TypeAnnotation? _awaited(TypeAnnotation? t) =>
      t is NamedType && t.name.lexeme == 'Future'
      ? t.typeArguments?.arguments.singleOrNull
      : t;

  TypeRef _ref(TypeAnnotation? t, String? native) {
    if (t is! NamedType) {
      return TypeRef(t?.toSource() ?? 'void', native: native);
    }
    return TypeRef(
      t.name.lexeme,
      args: [
        for (final a in t.typeArguments?.arguments ?? const <TypeAnnotation>[])
          _ref(a, null),
      ],
      nullability: t.question == null
          ? Nullability.nonNull
          : Nullability.nullable,
      native: native,
    );
  }

  /// The Java declaration in the leading ``/// from: `…` `` line.
  String? _from(AnnotatedNode? n) {
    final docs = _raw(n);
    if (docs == null || !docs.startsWith('from: `')) return null;
    final end = docs.indexOf('`', 7);
    return end < 0 ? null : docs.substring(7, end);
  }

  /// `public java.lang.String greet(java.lang.String name)` →
  /// name `greet`, type `java.lang.String`, params `[java.lang.String]`.
  ///
  /// `public suspend fun greetSlowly(name: kotlin.String): kotlin.String` →
  /// name `greetSlowly`, type `kotlin.String`, params `[kotlin.String]`,
  /// names `[name]`, suspend. A trailing `?` is left to the Dart type, which
  /// already says `JString?`.
  _Java? _signature(AnnotatedNode? n) {
    final from = _from(n);
    if (from == null || !from.contains(' ')) return null;
    final open = from.indexOf('(');
    final head = (open < 0 ? from : from.substring(0, open)).split(' ');
    if (head.length < 2) return null;
    final close = from.lastIndexOf(')');
    final args = open < 0
        ? const <String>[]
        : _split(from.substring(open + 1, close));
    // Kotlin puts the return type last: `…): kotlin.String where T : …`.
    if (open >= 0 && from.startsWith('): ', close)) {
      final names = <String>[];
      final params = <String>[];
      for (final a in args) {
        final colon = a.indexOf(': ');
        final name = a.substring(0, colon).trim();
        final type = a.substring(colon + 2).trim();
        // `vararg names: kotlin.String` is an array on the JVM.
        final vararg = name.startsWith('vararg ');
        names.add(vararg ? name.substring(7) : name);
        params.add(vararg ? 'kotlin.Array<out $type>' : _nonNull(type));
      }
      return (
        name: head.last,
        type: _nonNull(from.substring(close + 3).split(' where ').first),
        params: params,
        names: names,
        isSuspend: head.contains('suspend'),
        isSynthetic: false,
      );
    }
    return (
      name: head.last,
      type: head[head.length - 2],
      params: [
        for (final a in args)
          // `java.util.Map<java.lang.String, java.lang.Integer> m` —
          // the parameter name is everything after the last space.
          a.trim().substring(0, a.trim().lastIndexOf(' ')).trimRight(),
      ],
      names: [
        for (final a in args) a.trim().substring(a.trim().lastIndexOf(' ') + 1),
      ],
      isSuspend: false,
      isSynthetic: head.contains('synthetic'),
    );
  }

  String _nonNull(String type) =>
      type.endsWith('?') ? type.substring(0, type.length - 1) : type;

  /// Splits an argument list on commas outside `<…>`.
  List<String> _split(String args) {
    final out = <String>[];
    var depth = 0;
    var start = 0;
    for (var i = 0; i < args.length; i++) {
      switch (args[i]) {
        case '<':
          depth++;
        case '>':
          depth--;
        case ',' when depth == 0:
          out.add(args.substring(start, i));
          start = i + 1;
      }
    }
    final last = args.substring(start).trim();
    if (last.isNotEmpty) {
      out.add(last);
    }
    return out;
  }

  /// The doc comment jnigen wrote, verbatim.
  String? _raw(AnnotatedNode? n) {
    final tokens = n?.documentationComment?.tokens;
    if (tokens == null) return null;
    final text = [
      for (final t in tokens) t.lexeme.replaceFirst(RegExp(r'^///\s?'), ''),
    ].join('\n').trim();
    return text.isEmpty ? null : text;
  }

  /// The Java or Kotlin documentation alone, as markdown. jnigen adds a
  /// ``from: `…` `` line and a note on releasing the returned object, which
  /// describe its own binding rather than the API, and passes Javadoc's
  /// inline tags through as they are.
  String? _docs(AnnotatedNode? n) {
    final raw = _raw(n);
    if (raw == null) return null;
    final names = _signature(n)?.names;
    final paramLine = RegExp(r'^@param\s+(\w+)\s+');
    final text = [
      for (final line in raw.split('\n'))
        if (!line.startsWith('from: `') &&
            line != _releaseNote &&
            !(names != null &&
                switch (paramLine.matchAsPrefix(line.trim())) {
                  final m? => names.contains(m.group(1)!),
                  _ => false,
                }))
          line,
    ].join('\n').replaceAllMapped(_javadocTag, _markdown).trim();
    return text.isEmpty ? null : text;
  }
}

/// jnigen's note under every member that returns an object.
const _releaseNote =
    'The returned object must be released after use, by calling the '
    '[release] method.';

final _javadocTag = RegExp(r'\{@(code|literal|link|linkplain)\s+([^}]*)\}');

/// `{@code x}` → `` `x` ``; `{@link Greeter#greet}` → `` `Greeter.greet` ``,
/// or the link's label when it has one.

Map<String, String> _javadocParamDocs(String? raw, List<String>? names) {
  if (raw == null || names == null) return const {};
  final out = <String, String>{};
  final line = RegExp(r'^@param\s+(\w+)\s+(.*)$');
  for (final row in raw.split('\n')) {
    final trimmed = row.trim();
    if (line.matchAsPrefix(trimmed) case final m?) {
      final name = m.group(1)!;
      if (names.contains(name)) out[name] = m.group(2)!.trim();
    }
  }
  return out;
}

String _markdown(Match m) {
  final body = m[2]!.trim();
  if (!m[1]!.startsWith('link')) return '`$body`';
  final label = body.indexOf(RegExp(r'\s'));
  if (label > 0) return body.substring(label).trim();
  return '`${body.startsWith('#') ? body.substring(1) : body.replaceFirst('#', '.')}`';
}
