/// The Android side of a `jvm` binding (plan P3-4): the Gradle script a
/// package's Android library applies, and the R8 keep rules it hands to every
/// app. Both are emitted from the JVM driver's committed IR snapshots, so the
/// classes kept are the ones jnigen really bound.
library;

import 'dart:convert';
import 'dart:io';

import 'package:bindsmith/bindsmith.dart';
import 'package:test/test.dart';

import '../golden.dart';

Layout _layout(String android) => Layout(
  loadBindsmithConfig('''
name: my_sdk
output: lib/src/generated
platforms:
  android:
$android
'''),
  package: 'my_sdk',
);

const _biometric = '''
    driver: jvm
    deps:
      maven: ["androidx.biometric:biometric:1.2.0-alpha05"]
      repositories:
        - https://maven.google.com
        - https://repo1.maven.org/maven2
''';

List<Decl> _ir(String golden) => irFromJson(
  jsonDecode(File('test/drivers/goldens/$golden').readAsStringSync())
      as List<Object?>,
);

void main() {
  test('every bound class is kept, and nothing jnigen only stubbed', () {
    final ir = _ir('ktgreeter_jvm.ir.json');
    final rules = emitAndroidGlue(
      _layout(_biometric),
      ir,
    )[Layout.androidRules]!;
    expect(rules, startsWith('# GENERATED BY bindsmith — do not edit.\n'));
    for (final type in ir.whereType<TypeDecl>()) {
      final rule = '-keep class ${type.id} { *; }';
      expect(rules, type.isDropped ? isNot(contains(rule)) : contains(rule));
    }
    // A nested class keeps its binary name, which is how R8 spells it too.
    expect(
      rules,
      contains(r'-keep class com.example.ktgreeter.KtGreeter$Companion { *; }'),
    );
    // Sorted, so a driver that returns classes in another order cannot
    // rewrite the file (rule 6).
    final keeps = rules
        .split('\n')
        .where((l) => l.startsWith('-keep class com.'))
        .toList();
    expect(keeps, [...keeps]..sort());
    expectGolden('test/emit/goldens/android/bindsmith-rules.pro', rules);
  });

  test('a suspend fun keeps kotlin.coroutines, a Java binding does not', () {
    final kotlin = emitAndroidGlue(
      _layout(_biometric),
      _ir('ktgreeter_jvm.ir.json'),
    )[Layout.androidRules]!;
    expect(kotlin, contains('-keep class kotlin.coroutines.** { *; }'));

    final java = emitAndroidGlue(
      _layout(_biometric),
      _ir('greeter_jvm.ir.json'),
    )[Layout.androidRules]!;
    expect(java, isNot(contains('kotlin.coroutines')));
    expect(java, contains('-keep class com.example.greeter.Greeter { *; }'));
  });

  test('the Gradle script adds the Maven dependencies and the keep rules', () {
    final gradle = emitAndroidGlue(
      _layout(_biometric),
      _ir('ktgreeter_jvm.ir.json'),
    )[Layout.androidGradle]!;
    expect(gradle, startsWith('// GENERATED BY bindsmith — do not edit.\n'));
    expect(gradle, contains("apply from: 'bindsmith.gradle'"));
    expect(gradle, contains('ffiPlugin: true'));
    // The rules file sits beside the script, which Gradle resolves against.
    expect(gradle, contains("consumerProguardFiles 'bindsmith-rules.pro'"));
    expect(
      gradle,
      contains("implementation 'androidx.biometric:biometric:1.2.0-alpha05'"),
    );
    // Searched in the order configured, as the resolver searched them.
    expect(
      gradle,
      contains(
        "    maven { url 'https://maven.google.com' }\n"
        "    maven { url 'https://repo1.maven.org/maven2' }\n",
      ),
    );
    expectGolden('test/emit/goldens/android/bindsmith.gradle', gradle);
  });

  test('without repositories Maven Central is used, as the resolver does', () {
    final gradle = emitAndroidGlue(
      _layout('    driver: jvm\n    deps: { maven: ["a.b:c:1.0"] }'),
      const [],
    )[Layout.androidGradle]!;
    expect(gradle, contains('repositories {\n    mavenCentral()\n}'));
    expect(gradle, contains("implementation 'a.b:c:1.0'"));
  });

  test('without Maven dependencies there is nothing to add but the rules', () {
    final gradle = emitAndroidGlue(
      _layout('    driver: jvm'),
      const [],
    )[Layout.androidGradle]!;
    expect(gradle, isNot(contains('repositories {')));
    expect(gradle, isNot(contains('dependencies {')));
    expect(gradle, contains('consumerProguardFiles'));
  });

  test('a quote cannot break out of a Gradle literal', () {
    final layout = Layout(
      BindsmithConfig(
        name: 'my_sdk',
        output: 'lib/src/generated',
        facade: const FacadeConfig(library: 'lib/my_sdk.dart'),
        platforms: {
          Platform.android: PlatformConfig(
            driver: Driver.jvm,
            deps: DepsConfig(maven: [const Coordinate('a', 'b', "1'")]),
          ),
        },
      ),
      package: 'my_sdk',
    );
    expect(
      () => emitAndroidGlue(layout, const []),
      throwsA(
        isA<ArgumentError>().having(
          (e) => e.message,
          'message',
          contains('Gradle literal'),
        ),
      ),
    );
  });
}
