/// The Apple side of an Objective-C or Swift binding (plan P2-3): CocoaPods
/// and SwiftPM snippets that list the generated `.m` glue and the frameworks
/// to link.
library;

import 'package:bindsmith/bindsmith.dart';
import 'package:test/test.dart';

import '../golden.dart';

Layout _layout(String platform) => Layout(
  loadBindsmithConfig('''
name: my_sdk
output: lib/src/generated
platforms:
  $platform
'''),
  package: 'my_sdk',
);

void main() {
  test('the podspec snippet lists the glue under source_files', () {
    final snippets = emitAppleGlue(
      _layout('ios: { driver: objc, headers: [counter.h] }'),
      const [],
      platform: Platform.ios,
    );
    final podspec = snippets[applePodspecPath(Platform.ios)]!;
    expect(podspec, startsWith('# GENERATED BY bindsmith — do not edit.\n'));
    expect(podspec, contains("Classes/**/*.{h,m}'"));
    expect(podspec, contains("'../lib/src/generated/ios/objc.g.m'"));
    expect(podspec, contains("s.frameworks = 'Foundation'"));
    expect(podspec, contains('ffiPlugin: true'));
    expectGolden('test/emit/goldens/apple/ios.podspec.snippet', podspec);
  });

  test('the SwiftPM snippet lists the glue under sources', () {
    final snippets = emitAppleGlue(
      _layout('macos: { driver: swift, include: { types: [Greeter] } }'),
      const [],
      platform: Platform.macos,
    );
    final swiftpm = snippets[applePackageSwiftPath(Platform.macos)]!;
    expect(swiftpm, startsWith('// GENERATED BY bindsmith — do not edit.\n'));
    expect(swiftpm, contains("'../lib/src/generated/macos/swift.g.m'"));
    expect(swiftpm, contains('.linkedFramework("Foundation")'));
    expectGolden(
      'test/emit/goldens/apple/macos.Package.swift.snippet',
      swiftpm,
    );
  });

  test('the same layout and IR produce byte-identical snippets', () {
    final layout = _layout('ios: { driver: objc, headers: [counter.h] }');
    const ir = <Decl>[];
    final once = emitAppleGlue(layout, ir, platform: Platform.ios);
    final again = emitAppleGlue(layout, ir, platform: Platform.ios);
    expect(again, once);
  });

  test('only ios and macos produce Apple glue', () {
    final layout = _layout('linux: { driver: c, headers: [a.h] }');
    expect(
      () => emitAppleGlue(layout, const [], platform: Platform.linux),
      throwsArgumentError,
    );
  });
}
