/// Unit tests for the Swift bridge emitter, on hand-built IR.
///
/// The emitter is the second half of P7-1: the Swift driver records what
/// swift2objc could not carry into its `@objc` wrapper, and this turns those
/// records back into Swift that Objective-C — and therefore Dart — can see.
library;

import 'package:bindsmith/bindsmith.dart';
import 'package:test/test.dart';

final _dropped = [Marker.dropped('swift2objc left it out')];

Member _method(
  String name, {
  List<Param> params = const [],
  String returns = 'Void',
  bool isStatic = false,
  Async async = Async.none,
  String? docs,
}) => Member(
  name,
  kind: MemberKind.method,
  params: params,
  returns: TypeRef(returns),
  isStatic: isStatic,
  async: async,
  native: 'func $name(…) -> $returns',
  docs: docs,
  markers: _dropped,
);

TypeDecl _type(
  String name, {
  List<Member> members = const [],
  List<String> typeParams = const [],
  TypeKind kind = TypeKind.klass,
}) => TypeDecl(
  id: 's:$name',
  name: name,
  platform: Platform.macos,
  kind: kind,
  typeParams: typeParams,
  members: members,
);

/// The Objective-C class swift2objc generates for [name], as the Swift driver
/// reports it: its presence is what lets the bridge take a wrapper.
TypeDecl _wrapper(String name) => TypeDecl(
  id: name,
  name: '${name}Wrapper',
  platform: Platform.macos,
  kind: TypeKind.klass,
);

void main() {
  test('a dropped method becomes an @objc method that casts collections', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [
          _method(
            'greetAll',
            params: [Param('names', const TypeRef('[String]'), named: true)],
            returns: '[String]',
            docs: 'Greets everyone.',
          ),
        ],
      ),
    ]);

    expect(bridge.classes, {'GreeterBridge'});
    expect(
      bridge.source,
      startsWith(
        '// GENERATED BY bindsmith — do not edit.\n'
        '// bindsmith:begin generated\n'
        'import Foundation\n',
      ),
    );
    expect(
      bridge.source,
      contains('@objc public final class GreeterBridge: NSObject {'),
    );
    expect(bridge.source, contains('public var wrapped: Greeter'));
    // Dart holds the wrapper, and `wrappedInstance` is internal to the module
    // both files are compiled into.
    expect(
      bridge.source,
      contains('@objc public init(_ wrapper: GreeterWrapper) {'),
    );
    expect(bridge.source, contains('wrapped = wrapper.wrappedInstance'));
    expect(bridge.source, contains('/// Greets everyone.'));
    expect(
      bridge.source,
      contains('@objc public func greetAll(names: NSArray) -> NSArray {'),
    );
    expect(
      bridge.source,
      contains('return wrapped.greetAll(names: names as! [String]) as NSArray'),
    );
  });

  test('a member that needs no cast is passed straight through', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [
          _method(
            'shout',
            params: [Param('text', const TypeRef('String'), named: true)],
          ),
        ],
      ),
    ]);
    expect(bridge.source, contains('func shout(text: String) {'));
    // `Void` takes no `return`, and nothing is cast.
    expect(bridge.source, contains('wrapped.shout(text: text)\n'));
    expect(bridge.source, isNot(contains('as!')));
  });

  test('a positional parameter keeps its underscore', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [
          _method('echo', params: [Param('text', const TypeRef('String'))]),
        ],
      ),
    ]);
    expect(bridge.source, contains('func echo(_ text: String) {'));
    expect(bridge.source, contains('wrapped.echo(text)'));
  });

  test('a var property round-trips, a let property only reads', () {
    final property = Member(
      'items',
      kind: MemberKind.property,
      returns: const TypeRef('[String]'),
      native: 'var items: [String]',
      markers: _dropped,
    );
    final setter = Member(
      'items',
      kind: MemberKind.setter,
      params: [Param('value', const TypeRef('[String]'))],
      returns: const TypeRef('Void'),
      native: 'var items: [String]',
      markers: _dropped,
    );
    final both = emitSwiftBridge([
      _wrapper('Bag'),
      _type('Bag', members: [property, setter]),
    ]).source;
    expect(both, contains('@objc public var items: NSArray {'));
    expect(both, contains('get { wrapped.items as NSArray }'));
    expect(both, contains('set { wrapped.items = newValue as! [String] }'));

    final readOnly = emitSwiftBridge([
      _wrapper('Bag'),
      _type('Bag', members: [property]),
    ]).source;
    expect(readOnly, isNot(contains('set {')));
  });

  test('a static member goes through the type, not the instance', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [_method('reset', isStatic: true, returns: '[String]')],
      ),
    ]);
    expect(bridge.source, contains('@objc public static func reset()'));
    expect(bridge.source, contains('return Greeter.reset() as NSArray'));
  });

  test('what Objective-C cannot represent is refused, never emitted', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [
          _method('pair', returns: '(Int, Int)'),
          _method('later', returns: 'String', async: Async.stream),
          Member(
            '',
            kind: MemberKind.constructor,
            native: 'init(prefix: String)',
            markers: _dropped,
          ),
          _method('fine', returns: 'String'),
        ],
      ),
    ]);
    expect(bridge.source, contains('func fine() -> String'));
    expect(bridge.source, contains('// Not bridged:'));
    expect(bridge.source, contains('`(Int, Int)` is not representable'));
    expect(bridge.source, contains('a stream needs a subscription'));
    expect(bridge.source, contains('has to be written by hand'));
    // The refusal quotes the Swift declaration, but never emits it as code.
    expect(bridge.source, isNot(contains('@objc public func pair')));
    expect(bridge.source, isNot(contains('@objc public func later')));
  });

  test('an async member arrives on a completion handler', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [
          _method(
            'fetch',
            params: [Param('url', const TypeRef('String'), named: true)],
            returns: '[String]',
            async: Async.future,
          ),
          _method('warm', async: Async.future),
        ],
      ),
    ]);
    expect(
      bridge.source,
      contains(
        '@objc public func fetch(url: String, '
        'completion: @escaping (NSArray) -> Void) {',
      ),
    );
    expect(
      bridge.source,
      contains('completion(await wrapped.fetch(url: url) as NSArray)'),
    );
    // Nothing to hand back, so the handler takes no argument.
    expect(
      bridge.source,
      contains('@objc public func warm(completion: @escaping () -> Void) {'),
    );
    expect(bridge.source, contains('await wrapped.warm()'));
    expect(bridge.source, contains('completion()'));
  });

  test('a Swift type swift2objc did wrap travels as that wrapper', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _wrapper('Volume'),
      _type(
        'Greeter',
        members: [
          _method(
            'shout',
            params: [Param('at', const TypeRef('Volume'), named: true)],
            returns: 'Volume',
          ),
        ],
      ),
    ]);
    expect(
      bridge.source,
      contains('func shout(at: VolumeWrapper) -> VolumeWrapper {'),
    );
    expect(
      bridge.source,
      contains('return VolumeWrapper(wrapped.shout(at: at.wrappedInstance))'),
    );
  });

  test('a Swift-only type with no wrapper of its own is refused', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      // `Volume` is in the IR as a Swift struct and nothing wrapped it.
      _type('Volume', kind: TypeKind.struct),
      _type(
        'Greeter',
        members: [
          _method(
            'shout',
            params: [Param('at', const TypeRef('Volume'), named: true)],
          ),
        ],
      ),
    ]);
    expect(bridge.source, contains('`Volume` is not representable'));
    expect(bridge.source, isNot(contains('@objc public func shout')));
  });

  test('a generic type cannot be bridged at all, and says so', () {
    final bridge = emitSwiftBridge([
      _type(
        'Box',
        kind: TypeKind.struct,
        typeParams: ['T'],
        members: [_method('unwrap', returns: 'T')],
      ),
    ]);
    expect(bridge.classes, isEmpty);
    expect(
      bridge.source,
      contains('// Not bridged, and still reported by `bindsmith verify`:'),
    );
    expect(bridge.source, contains('Box: generic over <T>'));
  });

  test('without a wrapper the bridge says why Dart cannot reach it', () {
    final bridge = emitSwiftBridge([
      _type('Greeter', members: [_method('ping')]),
    ]);
    expect(bridge.classes, {'GreeterBridge'});
    expect(
      bridge.source,
      contains('// `GreeterWrapper` is not in the binding'),
    );
    expect(bridge.source, contains('public init(_ wrapped: Greeter) {'));
    expect(bridge.source, isNot(contains('@objc public init')));
  });

  test('a type with nothing dropped produces no bridge', () {
    final bridge = emitSwiftBridge([
      _wrapper('Greeter'),
      _type(
        'Greeter',
        members: [
          Member(
            'greet',
            kind: MemberKind.method,
            returns: const TypeRef('String'),
          ),
        ],
      ),
    ]);
    expect(bridge.classes, isEmpty);
    expect(
      bridge.source.trim(),
      '// GENERATED BY bindsmith — do not edit.\n'
      '// bindsmith:begin generated\n'
      'import Foundation\n'
      '// bindsmith:end generated',
    );
  });
}
